import { createGermanBuyerJourneyPage } from "./germanBuyerJourneyFactory";

const paired = (english: string, german: string) => [
  { locale: "en", href: english },
  { locale: "de", href: german },
];

export const GERMAN_BUYER_JOURNEY_PAGES = [
  createGermanBuyerJourneyPage({
    path: "/de/bavarian-wear",
    title: "Trachtenhersteller für Großhandel und Eigenmarken | Irha Apparels",
    description: "Kundenspezifische Trachtenfertigung für Großhändler, Fachhändler und Eigenmarken mit Lederhosen, Dirndl, Hemden, Westen, Accessoires, Größenläufen und Musterfreigabe.",
    h1: "Trachtenfertigung für Großhandel und Eigenmarken",
    eyebrow: "DACH · B2B-Trachtenbeschaffung",
    market: "Deutschland, Österreich und der Schweiz",
    productFocus: "Lederhosen-, Dirndl- und abgestimmte Trachtenprogramme",
    categoryPath: "/products/bavarian-trachten-wear",
    primaryLabel: "Trachtenprojekt anfragen",
    products: ["Lederhosen mit abgestimmten Hosenträgern", "Dirndl, Blusen und Schürzen", "Trachtenhemden, Westen und Janker", "Hüte, Socken, Gürtel und ausgewählte Accessoires"],
    specifications: ["Leder- und Stoffrichtung", "Stickerei, Besatz und Komponenten", "Größenlauf und Mengenverteilung", "Eigenmarken-Etiketten und Verpackung"],
    relatedPaths: ["/de/lederhosen-hersteller", "/de/dirndl-grosshandel", "/de/trachten-private-label", "/products/bavarian-trachten-wear", "/factory-video-call"],
    alternates: paired("/products/bavarian-trachten-wear", "/de/bavarian-wear"),
  }),
  createGermanBuyerJourneyPage({
    path: "/de/lederhosen-hersteller",
    title: "Lederhosen-Hersteller für Deutschland | Großhandel & Private Label",
    description: "Kundenspezifische Lederhosen-Fertigung für deutsche Großhändler, Trachtenhändler und Private-Label-Marken mit abgestimmtem Leder, Stickerei, Größenlauf und Musterfreigabe.",
    h1: "Lederhosen-Hersteller für Großhandel und Private Label",
    eyebrow: "Deutschland · B2B-Lederhosenfertigung",
    market: "Deutschland",
    productFocus: "kundenspezifische Lederhosen und abgestimmte Trachtenkomponenten",
    categoryPath: "/products/bavarian-trachten-wear",
    primaryLabel: "Lederhosen-Angebot anfragen",
    products: ["kurze, knielange und lange Lederhosen", "Stickereien und Kontrastnähte", "passende oder abnehmbare Hosenträger", "Eigenmarken-Etiketten und Handelsverpackung"],
    specifications: ["Lederart und Stärke", "Stickmotiv und Garnfarben", "Beschläge und Hosenträger", "Maßtabelle und Größenlauf"],
    relatedPaths: ["/de/bavarian-wear", "/de/trachten-private-label", "/de/dirndl-grosshandel", "/products/bavarian-trachten-wear", "/buyer-trust"],
    alternates: paired("/lederhosen-manufacturer-germany", "/de/lederhosen-hersteller"),
  }),
  createGermanBuyerJourneyPage({
    path: "/de/dirndl-grosshandel",
    title: "Dirndl-Hersteller für Großhandel | Private Label & Muster",
    description: "Kundenspezifische Dirndl-Fertigung für Großhändler, Trachtenhändler und Marken mit abgestimmtem Kleid, Bluse, Schürze, Größenlauf, Etiketten und Musterfreigabe.",
    h1: "Dirndl-Hersteller für Großhandel und Eigenmarken",
    eyebrow: "DACH · B2B-Dirndlfertigung",
    market: "Deutschland, Österreich und Schweiz",
    productFocus: "kundenspezifische Dirndl-Kleider, Blusen und Schürzen",
    categoryPath: "/products/bavarian-trachten-wear",
    primaryLabel: "Dirndl-Angebot anfragen",
    products: ["Mini-, Midi- und lange Dirndl", "klassische, Spitzen- und Puffärmel-Blusen", "Satin-, Baumwoll- und Spitzenschürzen", "abgestimmte Sets mit Eigenmarken-Ausstattung"],
    specifications: ["Silhouette und Rocklänge", "Stoff- und Besatzreferenzen", "Blusen- und Schürzenabstimmung", "Maßtabelle und Größenverteilung"],
    relatedPaths: ["/de/bavarian-wear", "/de/trachten-private-label", "/de/lederhosen-hersteller", "/products/bavarian-trachten-wear", "/factory-video-call"],
    alternates: paired("/dirndl-manufacturer-austria", "/de/dirndl-grosshandel"),
  }),
  createGermanBuyerJourneyPage({
    path: "/de/trachten-private-label",
    title: "Trachtenhersteller für Private Label | B2B-Kollektionen",
    description: "Private-Label-Trachtenfertigung für Großhändler und Marken: Lederhosen, Dirndl, Hemden, Westen, Janker, Accessoires, Etiketten und kundenspezifische Verpackung.",
    h1: "Private-Label-Trachtenhersteller für B2B-Kollektionen",
    eyebrow: "DACH · Trachten für Eigenmarken",
    market: "Deutschland, Österreich und Schweiz",
    productFocus: "Private-Label-Trachtenkollektionen und abgestimmte Accessoires",
    categoryPath: "/products/bavarian-trachten-wear",
    primaryLabel: "Private-Label-Projekt anfragen",
    products: ["Lederhosen und Hosenträger", "Dirndl, Blusen und Schürzen", "Trachtenhemden, Westen und Janker", "Hüte, Socken und ausgewählte Accessoires"],
    specifications: ["Sortiments- und Zielgruppenplanung", "Markenetiketten und Hangtags", "Artwork- und Platzierungsdaten", "Verpackungs- und Nachbestellanforderungen"],
    relatedPaths: ["/de/bavarian-wear", "/de/lederhosen-hersteller", "/de/dirndl-grosshandel", "/de/bekleidungshersteller-deutschland", "/products/bavarian-trachten-wear"],
    alternates: [{ locale: "de", href: "/de/trachten-private-label" }],
  }),
  createGermanBuyerJourneyPage({
    path: "/de/bekleidungshersteller-deutschland",
    title: "Bekleidungshersteller für Deutschland | OEM & Private Label",
    description: "Kundenspezifische Bekleidungsfertigung für deutsche Importeure, Großhändler, Fachhändler und Marken mit Musterentwicklung, Eigenmarken-Ausstattung und klarer Auftragsfreigabe.",
    h1: "Bekleidungshersteller für deutsche B2B-Einkäufer",
    eyebrow: "Deutschland · OEM- und Private-Label-Fertigung",
    market: "Deutschland",
    productFocus: "OEM- und Private-Label-Bekleidung für gewerbliche Einkäufer",
    categoryPath: "/products",
    primaryLabel: "B2B-Fertigungsanfrage senden",
    products: ["Trachten und Lederbekleidung", "Sportbekleidung und Teamwear", "Streetwear und Activewear", "Freizeit- und Nachtwäsche"],
    specifications: ["Produktreferenz oder Tech Pack", "Material und Zielqualität", "Größen und Mengenverteilung", "Branding, Verpackung und Lieferort"],
    relatedPaths: ["/de/", "/de/bavarian-wear", "/de/sportbekleidung-hersteller", "/de/lederbekleidung-hersteller", "/products"],
    alternates: paired("/germany-apparel-manufacturer", "/de/bekleidungshersteller-deutschland"),
  }),
  createGermanBuyerJourneyPage({
    path: "/de/sportbekleidung-hersteller",
    title: "Sportbekleidungshersteller für Deutschland | Teamwear & Private Label",
    description: "Kundenspezifische Sport- und Teamwear-Fertigung für deutsche Vereine, Händler und Marken mit Artwork-, Größen-, Muster- und Nachbestellfreigabe.",
    h1: "Sportbekleidungshersteller für Vereine, Händler und Marken",
    eyebrow: "Deutschland · Teamwear und Sportbekleidung",
    market: "Deutschland",
    productFocus: "kundenspezifische Teamwear, Trainingsbekleidung und Private-Label-Sportprogramme",
    categoryPath: "/products/sportswear",
    primaryLabel: "Sportbekleidungs-Angebot anfragen",
    products: ["Fußball-, Basketball-, Rugby-, Cricket- und Hockey-Sets", "Trainingsanzüge, Oberteile, Shorts und Hosen", "Vereins-, Akademie- und Händlerprogramme", "Spielernamen, Nummern und freigegebene Sponsorengrafiken"],
    specifications: ["Sportart und Einsatz", "Farben, Wappen und Artwork", "Materialgewicht und Elastizität", "Größen, Spielerlisten und Nachbestellbedarf"],
    relatedPaths: ["/de/", "/de/bekleidungshersteller-deutschland", "/de/lederbekleidung-hersteller", "/products/sportswear", "/repeat-order"],
    alternates: paired("/custom-sportswear-manufacturer-germany", "/de/sportbekleidung-hersteller"),
  }),
  createGermanBuyerJourneyPage({
    path: "/de/lederbekleidung-hersteller",
    title: "Lederbekleidungshersteller für Deutschland | Private Label",
    description: "Kundenspezifische Lederbekleidungsfertigung für deutsche Marken, Importeure und Großhändler mit abgestimmtem Leder, Futter, Beschlägen, Größen, Mustern und Etiketten.",
    h1: "Lederbekleidungshersteller für deutsche B2B-Einkäufer",
    eyebrow: "Deutschland · Lederbekleidung für B2B",
    market: "Deutschland",
    productFocus: "kundenspezifische Lederjacken, Westen, Hosen und Private-Label-Lederbekleidung",
    categoryPath: "/products/premium-leather-apparel",
    primaryLabel: "Lederbekleidungs-Angebot anfragen",
    products: ["Biker-, Bomber- und Fashion-Lederjacken", "Lederwesten und Hosen", "Gürtel, Handschuhe und ausgewählte Accessoires", "kundenspezifisches Futter, Patches, Etiketten und Verpackung"],
    specifications: ["Lederart, Stärke, Farbton und Griff", "Futter, Isolierung und Verstärkungen", "Reißverschlüsse, Druckknöpfe und Schnallen", "Passform, Gradierung und Toleranzen"],
    relatedPaths: ["/de/", "/de/bekleidungshersteller-deutschland", "/de/sportbekleidung-hersteller", "/products/premium-leather-apparel", "/buyer-trust"],
    alternates: paired("/leather-apparel-manufacturer-germany", "/de/lederbekleidung-hersteller"),
  }),
];

export const GERMAN_BUYER_JOURNEY_PATHS = GERMAN_BUYER_JOURNEY_PAGES.map((page) => page.path);
