import { PUBLIC_IDENTITY } from "./publicIdentity.mjs";

const categoryLinks = Object.freeze([
  Object.freeze({ href: "/products/bavarian-trachten-wear", label: "Bavarian & Trachten Wear" }),
  Object.freeze({ href: "/products/premium-leather-apparel", label: "Premium Leather Apparel" }),
  Object.freeze({ href: "/products/sportswear", label: "Custom Sportswear & Teamwear" }),
  Object.freeze({ href: "/products/streetwear-activewear", label: "Streetwear & Activewear" }),
  Object.freeze({ href: "/products/leisure-nightwear", label: "Leisurewear & Nightwear" }),
]);

const route = (definition) => Object.freeze({
  pageType: "WebPage",
  indexable: true,
  ...definition,
  breadcrumbs: Object.freeze([
    Object.freeze({ href: "/", label: "Home" }),
    Object.freeze({ href: definition.route, label: definition.breadcrumbLabel }),
  ]),
  sections: Object.freeze(definition.sections.map((section) => Object.freeze({
    ...section,
    items: section.items ? Object.freeze([...section.items]) : undefined,
    links: section.links ? Object.freeze(section.links.map((link) => Object.freeze({ ...link }))) : undefined,
  }))),
  primaryCta: Object.freeze(definition.primaryCta),
  secondaryCta: definition.secondaryCta ? Object.freeze(definition.secondaryCta) : undefined,
  parityTokens: Object.freeze(definition.parityTokens),
});

export const MAIN_CATEGORY_LINKS = categoryLinks;

export const CORE_ROUTE_CONTENT = Object.freeze({
  "/about": route({
    route: "/about",
    breadcrumbLabel: "About",
    pageType: "AboutPage",
    title: "About Irha Apparels — B2B Apparel Manufacturer in Sialkot",
    metaDescription: "Irha Apparels is a Sialkot-based B2B custom apparel manufacturer for brands, wholesalers and importers. Buyers can verify the public business identity and request direct contact.",
    eyebrow: "About Irha Apparels",
    h1: "Built for serious B2B programs.",
    intro: "Irha Apparels is a Sialkot-based custom apparel manufacturer working with brands, wholesalers, importers and private-label buyers who need requirement-led production.",
    sections: [
      {
        heading: "Public accountability",
        body: `${PUBLIC_IDENTITY.responsiblePerson.display} is the public business representative for ${PUBLIC_IDENTITY.name}. This statement does not assert legal ownership or registration status.`,
        items: [
          `Public location: ${PUBLIC_IDENTITY.address.display}`,
          `Business email: ${PUBLIC_IDENTITY.email}`,
          `Telephone and WhatsApp: ${PUBLIC_IDENTITY.telephone}`,
          `Availability: ${PUBLIC_IDENTITY.availability.days}, ${PUBLIC_IDENTITY.availability.hours}`,
          PUBLIC_IDENTITY.availability.appointmentPolicy,
        ],
      },
      {
        heading: "How buyers can verify and contact the company",
        body: "Buyers can review the published contact identity, submit a requirement, discuss a sample path and request an appointment-based factory video call before making a commercial commitment.",
        links: [
          { href: "/buyer-trust", label: "Review buyer verification paths" },
          { href: "/factory-video-call", label: "Request a factory video call" },
          { href: "/contact", label: "Contact Irha Apparels" },
        ],
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Start an inquiry" },
    secondaryCta: { href: "/contact", label: "View contact details" },
    sourceFile: "src/pages/About.tsx",
    parityTokens: ["Built for serious", "B2B programs", "Sialkot-based custom apparel manufacturer", "Daim Ali", "CEO"],
  }),
  "/contact": route({
    route: "/contact",
    breadcrumbLabel: "Contact",
    title: `Contact ${PUBLIC_IDENTITY.name} — ${PUBLIC_IDENTITY.address.display}`,
    metaDescription: `Reach ${PUBLIC_IDENTITY.name} via WhatsApp, email or direct call for B2B apparel manufacturing enquiries. Buyer visits and calls are arranged by prior appointment.`,
    eyebrow: "Contact",
    h1: "Let's build together.",
    intro: `Contact ${PUBLIC_IDENTITY.name} through the published business channels below. ${PUBLIC_IDENTITY.responsiblePerson.display} is the public responsible person for business buyers.`,
    sections: [
      {
        heading: "Official contact routes",
        body: "Use the channel that best fits the requirement. Commercial details are confirmed only after the actual program is reviewed.",
        items: [
          `Email: ${PUBLIC_IDENTITY.email}`,
          `Telephone / WhatsApp: ${PUBLIC_IDENTITY.telephone}`,
          `Public location: ${PUBLIC_IDENTITY.address.display}`,
          `Availability: ${PUBLIC_IDENTITY.availability.days}, ${PUBLIC_IDENTITY.availability.hours}`,
          PUBLIC_IDENTITY.availability.appointmentPolicy,
        ],
      },
      {
        heading: "Official profiles",
        body: "The published social profiles provide additional contact routes for Irha Apparels.",
        links: [
          { href: PUBLIC_IDENTITY.socialProfiles.instagram, label: "Instagram" },
          { href: PUBLIC_IDENTITY.socialProfiles.facebook, label: "Facebook" },
          { href: PUBLIC_IDENTITY.socialProfiles.linkedin, label: "LinkedIn" },
          { href: PUBLIC_IDENTITY.socialProfiles.tiktok, label: "TikTok" },
        ],
      },
    ],
    primaryCta: { href: `https://wa.me/${PUBLIC_IDENTITY.whatsappNumber}`, label: "Open WhatsApp" },
    secondaryCta: { href: "/inquiry", label: "Submit an inquiry" },
    sourceFile: "src/pages/Contact.tsx",
    parityTokens: ["Let's build", "together", "Responsible Person", "Business Availability", "Official Profiles"],
  }),
  "/manufacturing": route({
    route: "/manufacturing",
    breadcrumbLabel: "Manufacturing",
    title: "Manufacturing Process — Irha Apparels Sialkot",
    metaDescription: "How Irha Apparels reviews custom B2B apparel programs, from requirements and sample discussion to production planning, quality review and dispatch preparation.",
    eyebrow: "Manufacturing",
    h1: "From requirement to a reviewed production path.",
    intro: "Each program is reviewed against its actual construction, material, branding, quantity and destination needs before feasibility, pricing or timing are confirmed.",
    sections: [
      {
        heading: "Requirement-led workflow",
        body: "The working sequence is adjusted to the product and buyer brief rather than treated as a fixed universal promise.",
        items: [
          "Requirement review",
          "Development or sample discussion",
          "Material and construction alignment",
          "Production planning",
          "Quality review",
          "Packing and dispatch planning",
        ],
      },
      {
        heading: "Confirmation before commitment",
        body: "Materials, construction, decoration, labels, packaging, quantity, timing and commercial terms are reviewed for the actual program before confirmation.",
        links: [
          { href: "/resources#rfq-checklist", label: "Prepare an RFQ" },
          { href: "/buyer-trust", label: "Review buyer verification" },
        ],
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Submit manufacturing requirements" },
    secondaryCta: { href: "/factory-video-call", label: "Request a factory video call" },
    sourceFile: "src/pages/Manufacturing.tsx",
    parityTokens: ["From requirement to a", "reviewed production path", "Requirement Review", "Quality Review", "Dispatch Preparation"],
  }),
  "/buyer-trust": route({
    route: "/buyer-trust",
    breadcrumbLabel: "Buyer Trust",
    title: "Buyer Trust Center — Verify Irha Apparels Before Ordering",
    metaDescription: "How B2B buyers can verify Irha Apparels through public contact identity, requirement review, sample discussion, factory video-call requests and written program details.",
    eyebrow: "Buyer Trust Center",
    h1: "Verify the supplier before the order.",
    intro: "Use direct contact, relevant evidence, clear specifications and documented approvals to evaluate a proposed program before making a commercial commitment.",
    sections: [
      {
        heading: "Verification paths",
        body: "The available verification path depends on the buyer requirement and the evidence relevant to that program.",
        items: [
          "Published public contact identity",
          "Requirement-led quotation review",
          "Sample and specification discussion",
          "Appointment-based factory video-call request",
          "Written product, branding and packaging review",
        ],
      },
      {
        heading: "Record the agreed scope",
        body: "Keep quotation details, specifications, sample decisions, requested changes, packaging and dispatch information connected to the same inquiry or order reference.",
        links: [
          { href: "/faq", label: "Read buyer questions" },
          { href: "/resources", label: "Use buyer checklists" },
        ],
      },
    ],
    primaryCta: { href: "/factory-video-call", label: "Request a factory video call" },
    secondaryCta: { href: "/inquiry?intent=rfq", label: "Submit a requirement" },
    sourceFile: "src/pages/BuyerTrust.tsx",
    parityTokens: ["Verify the supplier", "before the order", "Requirement-led quotation", "Approval before bulk", "Program-specific documentation"],
  }),
  "/factory-video-call": route({
    route: "/factory-video-call",
    breadcrumbLabel: "Factory Video Call",
    title: "Request a Live Factory Video Call | Irha Apparels",
    metaDescription: "Request an appointment-based live video call with Irha Apparels to discuss a B2B apparel program. A requested time is not automatically booked and availability must be confirmed.",
    eyebrow: "Live factory verification",
    h1: "Meet the team and view the factory live.",
    intro: "A factory video call is a request, not an automatic booking. The team reviews the product category, preferred time and requested scope before confirming availability.",
    sections: [
      {
        heading: "What happens after a request",
        body: "The call is arranged only after the request has been reviewed.",
        items: [
          "Submit the meeting topic, preferred time window and contact details",
          "The team reviews the category and confirms availability and viewing scope",
          "A confirmed time and communication channel are provided before the call",
        ],
      },
      {
        heading: "Prepare the discussion",
        body: "Share the product category, order structure, reference files and questions that the buying or quality team wants covered.",
      },
    ],
    primaryCta: { href: "/inquiry?intent=meeting", label: "Request a meeting" },
    secondaryCta: { href: "/buyer-trust", label: "Review buyer verification" },
    sourceFile: "src/pages/FactoryVideoCall.tsx",
    parityTokens: ["Meet the team and view the factory", "live", "A requested time is not automatically booked", "Availability is confirmed after review"],
  }),
  "/inquiry": route({
    route: "/inquiry",
    breadcrumbLabel: "Inquiry",
    title: "B2B Inquiry — Quote, Sample, Catalogue | Irha Apparels",
    metaDescription: "Send a B2B inquiry to Irha Apparels for a quotation, sample, catalogue, reference or tech-pack upload, or an appointment-based meeting request.",
    eyebrow: "B2B Inquiry",
    h1: "Tell us what you need.",
    intro: "Choose the inquiry intent that matches the next step. Submitted details are reviewed before product feasibility, commercial terms or meeting availability are confirmed.",
    sections: [
      {
        heading: "Available inquiry intents",
        body: "The inquiry workflow supports the following current request types.",
        items: [
          "Quotation request",
          "Sample request",
          "Catalogue request",
          "Reference, artwork, mockup or tech-pack upload",
          "Meeting or factory-call request",
        ],
      },
      {
        heading: "Information used for review",
        body: "Product, quantity, material, branding, packaging, destination, reference files and buyer contact details can be provided through the form. Private submitted data is not reproduced in this static page content.",
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Request a quotation" },
    secondaryCta: { href: "/contact", label: "Use direct contact" },
    sourceFile: "src/pages/InquiryBase.tsx",
    parityTokens: ["Tell us what you need", "Request Quote", "Request Sample", "Request Catalogue", "Upload Reference", "Request Meeting"],
  }),
  "/privacy-policy": route({
    route: "/privacy-policy",
    breadcrumbLabel: "Privacy Policy",
    title: "Privacy Policy — Irha Apparels",
    metaDescription: "How Irha Apparels handles website analytics choices, visitor presence, inquiry details, live-chat typing previews, uploaded files and local inquiry drafts.",
    eyebrow: "Privacy",
    h1: "Privacy Policy",
    intro: "This policy explains how the Irha Apparels website handles visitor choices, website presence, inquiry details and files submitted for B2B requirement review.",
    sections: [
      {
        heading: "Information covered by this policy",
        body: "The policy covers optional analytics choices, essential website-presence records, live-chat typing previews, submitted inquiry information, uploaded reference files and inquiry drafts stored in the buyer's browser.",
      },
      {
        heading: "Use and contact",
        body: `Submitted information and essential website-presence data are used to review requirements, respond to inquiries, provide support, maintain security and manage follow-up. Privacy questions can be sent to ${PUBLIC_IDENTITY.email}.`,
      },
    ],
    primaryCta: { href: `mailto:${PUBLIC_IDENTITY.email}`, label: "Email a privacy question" },
    secondaryCta: { href: "/contact", label: "View contact details" },
    sourceFile: "src/pages/PrivacyPolicy.tsx",
    parityTokens: ["Privacy Policy", "Cookies and analytics", "Live chat and typing preview", "Uploaded files", "Inquiry drafts on your device"],
  }),
  "/compliance": route({
    route: "/compliance",
    breadcrumbLabel: "Compliance",
    title: "Compliance & Documentation Review | Irha Apparels",
    metaDescription: "Share buyer, material, documentation and destination requirements with Irha Apparels for program-specific review before production commitments are made.",
    eyebrow: "Compliance & Documentation",
    h1: "Requirements first. Evidence before claims.",
    intro: "Send the exact documentation, material or destination requirements for the proposed program. They are reviewed before the team confirms what can be supplied or supported.",
    sections: [
      {
        heading: "Program-specific review",
        body: "Buyer manuals, quality checklists, material preferences and requested commercial or shipment documents can be reviewed against the proposed program.",
        items: [
          "Documentation review",
          "Buyer requirements and checklists",
          "Destination requirement review",
          "Buyer-specified material review",
          "Certification requests confirmed only when valid evidence is available",
        ],
      },
    ],
    primaryCta: { href: "/inquiry?intent=reference", label: "Share a requirement" },
    secondaryCta: { href: "/buyer-trust", label: "Review verification paths" },
    sourceFile: "src/pages/Compliance.tsx",
    parityTokens: ["Requirements first", "Evidence before claims", "Documentation Review", "Certification Requests", "No assumptions"],
  }),
  "/products": route({
    route: "/products",
    breadcrumbLabel: "Products",
    pageType: "CollectionPage",
    title: "Custom Apparel Manufacturing Categories | Wholesale & Private Label | Irha Apparels",
    metaDescription: "Browse Irha Apparels by main category, buyer group, product type and current products. Each route leads directly to the relevant catalogue styles.",
    eyebrow: "Product Catalogue",
    h1: "Browse by category, buyer group and product type.",
    intro: "Choose a manufacturing category, then browse Men, Women, Kids or the relevant buyer group. Each audience opens focused product categories and individual styles for quotation.",
    sections: [
      {
        heading: "Five main product categories",
        body: "Open the current product categories below. Each category is organised by buyer group and product type.",
        links: categoryLinks,
      },
      {
        heading: "Requirement-led quotation",
        body: "Select the closest category or product, then submit the actual quantity, specification, branding, packaging and reference details for review.",
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Request a quotation" },
    secondaryCta: { href: "/products/all", label: "Search all products" },
    sourceFile: "src/pages/GlobalCollectionsPage.tsx",
    parityTokens: ["Browse by category", "buyer group and product type", "Men, Women, Kids", "Browse products"],
  }),
  "/faq": route({
    route: "/faq",
    breadcrumbLabel: "Buyer FAQ",
    title: "B2B Buyer FAQ — Quotes, Samples, MOQ & Verification",
    metaDescription: "Buyer-safe answers about Irha Apparels verification, custom quotations, MOQ review, samples, private label, production, documentation, shipping and payment.",
    eyebrow: "B2B Buyer FAQ",
    h1: "Clear answers before you request a quote.",
    intro: "The published answers explain the working approach. Exact MOQ, price, sample cost, production timing, documents and shipping are confirmed only after the specific program is reviewed.",
    sections: [
      {
        heading: "Questions tied to the actual program",
        body: "Use the FAQ for general process guidance, then send the exact product and commercial context when a program-specific answer is required.",
        links: [
          { href: "/buyer-trust", label: "Open the Buyer Trust Center" },
          { href: "/resources", label: "Use buyer sourcing checklists" },
        ],
      },
    ],
    primaryCta: { href: "/inquiry", label: "Send an inquiry" },
    secondaryCta: { href: "/factory-video-call", label: "Request a factory call" },
    sourceFile: "src/pages/FAQ.tsx",
    parityTokens: ["Clear answers before you", "request a quote", "Exact MOQ", "Buyer Trust Center"],
  }),
  "/resources": route({
    route: "/resources",
    breadcrumbLabel: "Buyer Resources",
    pageType: "CollectionPage",
    title: "B2B Apparel Buyer Resources | RFQ, Samples & Sourcing",
    metaDescription: "Practical B2B apparel sourcing checklists for preparing an RFQ, approving samples, comparing quotations, understanding OEM or ODM and planning shipping discussions.",
    eyebrow: "Buyer Resources",
    h1: "Better sourcing starts with better questions.",
    intro: "Use these practical checklists to prepare requirements, compare suppliers and reduce ambiguity before sampling or production. They are general buyer guidance, not fixed terms for every Irha Apparels order.",
    sections: [
      {
        heading: "Published buyer guides",
        body: "Open the relevant checklist for the current sourcing step.",
        links: [
          { href: "/resources#rfq-checklist", label: "RFQ checklist" },
          { href: "/resources#sample-approval", label: "Sample approval checklist" },
          { href: "/resources#oem-odm-private-label", label: "OEM, ODM and private label" },
          { href: "/resources#quote-comparison", label: "How to compare quotations" },
          { href: "/resources#shipping-questions", label: "Shipping questions to settle" },
        ],
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Prepare an RFQ" },
    secondaryCta: { href: "/faq", label: "Read buyer FAQ" },
    sourceFile: "src/pages/BuyerResources.tsx",
    parityTokens: ["Better sourcing starts with", "better questions", "RFQ checklist", "Sample approval checklist", "How to compare quotations"],
  }),
  "/terms-of-service": route({
    route: "/terms-of-service",
    breadcrumbLabel: "Website Terms",
    title: "Website Terms | Irha Apparels",
    metaDescription: "Website terms for Irha Apparels. Commercial order terms, pricing, payment, production, shipping and claims are confirmed separately for each B2B order.",
    eyebrow: "Website Terms",
    h1: "General website terms. Order terms are separate.",
    intro: "These terms govern use of the Irha Apparels website and inquiry tools. They do not create a final quotation, purchase contract, price, payment term, delivery promise or manufacturing commitment.",
    sections: [
      {
        heading: "Website content is not a final order commitment",
        body: "Product pages, concept previews, forms, messages and general website content support requirement discussion. Final feasibility and commercial terms are confirmed through order-specific documents.",
      },
      {
        heading: "Buyer-provided files and approvals",
        body: "Buyers are responsible for the rights to submitted logos, artwork, designs and trademarks. Sample, specification, branding and confidentiality requirements should be agreed in writing for the actual program.",
      },
    ],
    primaryCta: { href: "/inquiry?intent=rfq", label: "Start an inquiry" },
    secondaryCta: { href: "/contact", label: "Contact the team" },
    sourceFile: "src/pages/TermsOfService.tsx",
    parityTokens: ["General website terms", "Order terms are separate", "Inquiry content is not a final quote", "Order-specific commercial terms"],
  }),
  "/repeat-order": route({
    route: "/repeat-order",
    breadcrumbLabel: "Repeat Order",
    title: "Repeat Order Request | Existing B2B Buyers — Irha Apparels",
    metaDescription: "Submit a repeat-order or existing-program request using a previous Irha Apparels order or inquiry reference. Changes are reviewed before confirmation.",
    eyebrow: "Existing buyer workflow",
    h1: "Request a repeat order.",
    intro: "Use the previous order, proforma invoice or inquiry reference so the team can locate the existing program. Materials, quantity, requested changes, pricing and timing are reviewed before confirmation.",
    sections: [
      {
        heading: "Keep the earlier reference ready",
        body: "An order number, proforma invoice number or inquiry reference helps the team locate the previously approved program. A repeat request is not an automatic production instruction.",
        items: [
          "Previous order or inquiry reference",
          "Product and requested quantity",
          "Requested changes, if any",
          "Current buyer and contact details",
        ],
      },
    ],
    primaryCta: { href: "/repeat-order#repeat-order-form", label: "Submit a repeat-order request" },
    secondaryCta: { href: "/contact", label: "Contact the team" },
    sourceFile: "src/pages/RepeatOrder.tsx",
    parityTokens: ["Request a", "repeat order", "Keep the earlier reference ready", "previous order or inquiry reference"],
  }),
  "/connect": route({
    route: "/connect",
    breadcrumbLabel: "Connect",
    title: "Connect with Irha Apparels — B2B Apparel Manufacturing",
    metaDescription: "Contact Irha Apparels in Sialkot about a custom B2B apparel requirement through the universal contact form or an official published channel.",
    eyebrow: "Universal Contact",
    h1: "Get in touch with Irha Apparels",
    intro: "Share the product, company and contact details so the team can review the request and reply using the information provided.",
    sections: [
      {
        heading: "Published channels",
        body: "The form and official profiles provide alternate ways to reach the business team.",
        links: [
          { href: PUBLIC_IDENTITY.socialProfiles.instagram, label: "Instagram" },
          { href: PUBLIC_IDENTITY.socialProfiles.facebook, label: "Facebook" },
          { href: PUBLIC_IDENTITY.socialProfiles.linkedin, label: "LinkedIn" },
          { href: PUBLIC_IDENTITY.socialProfiles.tiktok, label: "TikTok" },
          { href: `https://wa.me/${PUBLIC_IDENTITY.whatsappNumber}`, label: "WhatsApp" },
        ],
      },
    ],
    primaryCta: { href: "/connect#connect-form", label: "Open the contact form" },
    secondaryCta: { href: "/contact", label: "View direct contact details" },
    sourceFile: "src/pages/Connect.tsx",
    parityTokens: ["Universal Contact", "Get in touch with", "Irha Apparels", "One form, every channel"],
  }),
});

export const CORE_ROUTE_PATHS = Object.freeze(Object.keys(CORE_ROUTE_CONTENT));
