import type { DbProduct } from "@/hooks/useCatalog";

// Final visually verified first-party Drive catalogue completion for Men, Women and Kids.
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "");

type Audience = "men" | "women" | "kids";

type ProductSeed = {
  id: number;
  audience: Audience;
  slug: string;
  name: string;
  productFamily: string;
  visual: string;
  features: string[];
  sort: number;
  image: string;
};

const PRODUCTS: ProductSeed[] = [
  {
    id: 950001,
    audience: "men",
    slug: "blue-gingham-trachten-shirt",
    name: "Blue Gingham Trachten Shirt",
    productFamily: "men's Trachten shirt",
    visual: "blue-and-white gingham presentation",
    features: ["Traditional button-front profile", "Contrast inner-collar detail", "Long-sleeve construction"],
    sort: 1400,
    image: "/media/bavarian-drive/assets/men-shirts/bavarian-men-s-checkered-shirt/trachten-shirts.webp",
  },
  {
    id: 950002,
    audience: "men",
    slug: "green-gingham-trachten-shirt",
    name: "Green Gingham Trachten Shirt",
    productFamily: "men's Trachten shirt",
    visual: "green-and-white gingham presentation",
    features: ["Traditional button-front profile", "Chest-pocket construction", "Long-sleeve construction"],
    sort: 1401,
    image: "/media/bavarian-drive/assets/men-shirts/bavarian-men-s-checkered-shirt/trachten-shirts-4.webp",
  },
  {
    id: 950003,
    audience: "men",
    slug: "lilac-micro-gingham-trachten-shirt",
    name: "Lilac Micro-Gingham Trachten Shirt",
    productFamily: "men's Trachten shirt",
    visual: "lilac micro-gingham presentation",
    features: ["Fine check pattern", "Traditional button-front profile", "Long-sleeve construction"],
    sort: 1402,
    image: "/media/bavarian-drive/assets/men-shirts/bavarian-men-s-checkered-shirt/trachten-shirts-8.webp",
  },
  {
    id: 950004,
    audience: "men",
    slug: "white-traditional-trachten-shirt",
    name: "White Traditional Trachten Shirt",
    productFamily: "men's Trachten shirt",
    visual: "clean white presentation",
    features: ["Traditional collar profile", "Button-front construction", "Long-sleeve silhouette"],
    sort: 1403,
    image: "/media/bavarian-drive/assets/men-shirts/bavarian-men-s-checkered-shirt/white-shirts.webp",
  },
  {
    id: 950005,
    audience: "men",
    slug: "traditional-graphic-trachten-t-shirt",
    name: "Traditional Graphic Trachten T-Shirt",
    productFamily: "men's Trachten T-shirt",
    visual: "traditional graphic-front presentation",
    features: ["Crew-neck silhouette", "Short-sleeve construction", "Buyer-specified graphic placement"],
    sort: 1404,
    image: "/media/bavarian-drive/assets/men-shirts/review-only/traditional-t-shirts.webp",
  },
  {
    id: 950006,
    audience: "men",
    slug: "black-embroidered-long-leather-trousers",
    name: "Black Embroidered Long Leather Trousers",
    productFamily: "men's long Trachten trousers",
    visual: "black presentation with decorative embroidery",
    features: ["Full-length silhouette", "Decorative front-panel embroidery", "Traditional waist construction"],
    sort: 1405,
    image: "/media/bavarian-drive/assets/men-leather-pants/leather-trousers/01.webp",
  },
  {
    id: 950007,
    audience: "men",
    slug: "dark-brown-embroidered-long-leather-trousers",
    name: "Dark Brown Embroidered Long Leather Trousers",
    productFamily: "men's long Trachten trousers",
    visual: "dark brown presentation with tonal embroidery",
    features: ["Full-length silhouette", "Traditional front-flap styling", "Decorative leg embroidery"],
    sort: 1406,
    image: "/media/bavarian-drive/assets/men-leather-pants/leather-trousers/long-leather-pants-0.webp",
  },
  {
    id: 950008,
    audience: "men",
    slug: "tan-buckle-waist-long-leather-trousers",
    name: "Tan Buckle-Waist Long Leather Trousers",
    productFamily: "men's long Trachten trousers",
    visual: "tan distressed presentation",
    features: ["Full-length silhouette", "Decorative buckle-waist detail", "Traditional pocket shaping"],
    sort: 1407,
    image: "/media/bavarian-drive/assets/men-leather-pants/leather-trousers/long-leather-pants-9.webp",
  },
  {
    id: 950009,
    audience: "men",
    slug: "grey-red-collar-classic-janker",
    name: "Grey Red-Collar Classic Janker",
    productFamily: "men's Trachten jacket",
    visual: "grey presentation with red contrast collar",
    features: ["Classic short Janker silhouette", "Contrast collar and piping", "Decorative button-front construction"],
    sort: 1408,
    image: "/media/bavarian-drive/assets/men-waistcoats-jackets/bavarian-embroidered-vest/traditional-costumes-0.webp",
  },
  {
    id: 950010,
    audience: "men",
    slug: "brown-yoke-two-tone-janker",
    name: "Brown-Yoke Two-Tone Janker",
    productFamily: "men's Trachten jacket",
    visual: "two-tone presentation with brown shoulder yoke",
    features: ["Classic tailored silhouette", "Contrast shoulder and collar panels", "Decorative button-front construction"],
    sort: 1409,
    image: "/media/bavarian-drive/assets/men-waistcoats-jackets/bavarian-embroidered-vest/traditional-costumes-4.webp",
  },
  {
    id: 950011,
    audience: "women",
    slug: "blue-cold-shoulder-gingham-trachten-blouse",
    name: "Blue Cold-Shoulder Gingham Trachten Blouse",
    productFamily: "women's Trachten blouse",
    visual: "blue-and-white gingham presentation",
    features: ["Cold-shoulder sleeve shaping", "Button-front construction", "Fitted waist profile"],
    sort: 1410,
    image: "/media/bavarian-drive/assets/women-shirts/review-only/traditional-shirts.webp",
  },
  {
    id: 950012,
    audience: "women",
    slug: "white-ruffle-trim-trachten-blouse",
    name: "White Ruffle-Trim Trachten Blouse",
    productFamily: "women's Trachten blouse",
    visual: "clean white presentation",
    features: ["Ruffle-trim neckline", "Fitted button-front bodice", "Short puff-sleeve construction"],
    sort: 1411,
    image: "/media/bavarian-drive/assets/women-shirts/review-only/traditional-shirts-4.webp",
  },
  {
    id: 950013,
    audience: "women",
    slug: "green-puff-sleeve-gingham-trachten-blouse",
    name: "Green Puff-Sleeve Gingham Trachten Blouse",
    productFamily: "women's Trachten blouse",
    visual: "green-and-white gingham presentation",
    features: ["Short puff sleeves", "Button-front bodice", "Fitted waist shaping"],
    sort: 1412,
    image: "/media/bavarian-drive/assets/women-shirts/review-only/traditional-shirts-8.webp",
  },
  {
    id: 950014,
    audience: "women",
    slug: "blue-corset-lace-trachten-blouse",
    name: "Blue Corset-Lace Trachten Blouse",
    productFamily: "women's Trachten blouse",
    visual: "blue check presentation with contrast lacing",
    features: ["Corset-inspired front lacing", "Short puff sleeves", "Fitted bodice profile"],
    sort: 1413,
    image: "/media/bavarian-drive/assets/women-shirts/review-only/traditional-shirts-12.webp",
  },
  {
    id: 950015,
    audience: "women",
    slug: "olive-floral-trim-trachten-skirt",
    name: "Olive Floral-Trim Trachten Skirt",
    productFamily: "women's Trachten skirt",
    visual: "olive presentation with decorative floral trim",
    features: ["Knee-length flared silhouette", "Decorative lower-border motif", "Structured waistband"],
    sort: 1414,
    image: "/media/bavarian-drive/assets/women-skirts/review-only/aa-5103a-1200x1200.webp",
  },
  {
    id: 950016,
    audience: "women",
    slug: "dark-brown-ornate-trachten-skirt",
    name: "Dark Brown Ornate Trachten Skirt",
    productFamily: "women's Trachten skirt",
    visual: "dark brown presentation with ornate lower-panel detail",
    features: ["Flared traditional silhouette", "Decorative lower-border panel", "Structured waistband"],
    sort: 1415,
    image: "/media/bavarian-drive/assets/women-skirts/review-only/aa-5106a-1200x1200.webp",
  },
  {
    id: 950017,
    audience: "women",
    slug: "mustard-embroidered-trachten-skirt",
    name: "Mustard Embroidered Trachten Skirt",
    productFamily: "women's Trachten skirt",
    visual: "mustard presentation with contrast embroidery",
    features: ["Flared knee-length silhouette", "Decorative embroidered border", "Structured waistband"],
    sort: 1416,
    image: "/media/bavarian-drive/assets/women-skirts/review-only/aa-5107a-1200x1200.webp",
  },
  {
    id: 950018,
    audience: "women",
    slug: "grey-embroidered-trachten-skirt",
    name: "Grey Embroidered Trachten Skirt",
    productFamily: "women's Trachten skirt",
    visual: "grey presentation with ornamental embroidery",
    features: ["Traditional flared silhouette", "Decorative lower-border embroidery", "Structured waistband"],
    sort: 1417,
    image: "/media/bavarian-drive/assets/women-skirts/review-only/aa-5109a-1200x1200.webp",
  },
  {
    id: 950019,
    audience: "women",
    slug: "chocolate-embroidered-trachten-skirt",
    name: "Chocolate Embroidered Trachten Skirt",
    productFamily: "women's Trachten skirt",
    visual: "chocolate-brown presentation with contrast embroidery",
    features: ["Traditional flared silhouette", "Decorative border detailing", "Structured waistband"],
    sort: 1418,
    image: "/media/bavarian-drive/assets/women-skirts/review-only/aa-5110a-1200x1200.webp",
  },
  {
    id: 950020,
    audience: "women",
    slug: "tan-buckle-waist-leather-trousers",
    name: "Tan Buckle-Waist Leather Trousers",
    productFamily: "women's Trachten trousers",
    visual: "tan presentation with decorative waist hardware",
    features: ["Slim full-length silhouette", "Buckle-waist detailing", "Traditional pocket shaping"],
    sort: 1419,
    image: "/media/bavarian-drive/assets/women-pents/review-only/01-1200x1200-1.webp",
  },
  {
    id: 950021,
    audience: "women",
    slug: "red-slim-fit-leather-trousers",
    name: "Red Slim-Fit Leather Trousers",
    productFamily: "women's Trachten trousers",
    visual: "red slim-fit presentation",
    features: ["Full-length fitted silhouette", "Traditional front-panel shaping", "Decorative waist detailing"],
    sort: 1420,
    image: "/media/bavarian-drive/assets/women-pents/review-only/02-1200x1200-1.webp",
  },
  {
    id: 950022,
    audience: "women",
    slug: "black-slim-fit-leather-trousers",
    name: "Black Slim-Fit Leather Trousers",
    productFamily: "women's Trachten trousers",
    visual: "black slim-fit presentation",
    features: ["Full-length fitted silhouette", "Traditional pocket shaping", "Decorative waist construction"],
    sort: 1421,
    image: "/media/bavarian-drive/assets/women-pents/review-only/04-1200x1200-1.webp",
  },
  {
    id: 950023,
    audience: "kids",
    slug: "grey-suspender-kids-lederhosen-set",
    name: "Grey Suspender Kids Lederhosen Set",
    productFamily: "kids' Trachten set",
    visual: "grey coordinated set presentation",
    features: ["Adjustable suspender Lederhosen", "Coordinated shirt styling", "Traditional embroidered details"],
    sort: 1422,
    image: "/media/bavarian-drive/assets/children/review-only/03-1200x1200.webp",
  },
  {
    id: 950024,
    audience: "kids",
    slug: "red-suspender-kids-lederhosen-set",
    name: "Red Suspender Kids Lederhosen Set",
    productFamily: "kids' Trachten set",
    visual: "red coordinated set presentation",
    features: ["Adjustable suspender Lederhosen", "Coordinated check shirt styling", "Traditional decorative details"],
    sort: 1423,
    image: "/media/bavarian-drive/assets/children/review-only/04-1200x1200-2.webp",
  },
  {
    id: 950025,
    audience: "kids",
    slug: "royal-blue-contrast-kids-trachten-waistcoat",
    name: "Royal Blue Contrast Kids Trachten Waistcoat",
    productFamily: "kids' Trachten waistcoat",
    visual: "royal blue presentation with contrast trim",
    features: ["Traditional stand-collar profile", "Decorative button front", "Contrast pocket and collar trim"],
    sort: 1424,
    image: "/media/bavarian-drive/assets/children/review-only/waiscoats.webp",
  },
  {
    id: 950026,
    audience: "kids",
    slug: "forest-green-kids-trachten-waistcoat",
    name: "Forest Green Kids Trachten Waistcoat",
    productFamily: "kids' Trachten waistcoat",
    visual: "forest green traditional presentation",
    features: ["Traditional stand-collar profile", "Decorative button front", "Contrast pocket trim"],
    sort: 1425,
    image: "/media/bavarian-drive/assets/children/review-only/waiscoats-2.webp",
  },
  {
    id: 950027,
    audience: "kids",
    slug: "lime-gingham-kids-trachten-shirt",
    name: "Lime Gingham Kids Trachten Shirt",
    productFamily: "kids' Trachten shirt",
    visual: "lime-and-white gingham presentation",
    features: ["Traditional button-front profile", "Long-sleeve construction", "Chest-pocket detail"],
    sort: 1426,
    image: "/media/bavarian-drive/assets/children/review-only/shirts.webp",
  },
  {
    id: 950028,
    audience: "kids",
    slug: "grey-deer-graphic-kids-trachten-t-shirt",
    name: "Grey Deer-Graphic Kids Trachten T-Shirt",
    productFamily: "kids' Trachten T-shirt",
    visual: "grey graphic-front presentation",
    features: ["Crew-neck silhouette", "Short-sleeve construction", "Traditional deer graphic placement"],
    sort: 1427,
    image: "/media/bavarian-drive/assets/children/review-only/t-shirts.webp",
  },
  {
    id: 950029,
    audience: "kids",
    slug: "brown-kids-haferl-shoes",
    name: "Brown Kids Haferl Shoes",
    productFamily: "kids' Trachten footwear",
    visual: "brown traditional footwear presentation",
    features: ["Low-cut Haferl-inspired profile", "Structured lace-up upper", "Buyer-specified outsole construction"],
    sort: 1428,
    image: "/media/bavarian-drive/assets/children/review-only/shoes-socks.webp",
  },
  {
    id: 950030,
    audience: "kids",
    slug: "grey-knee-high-kids-trachten-socks",
    name: "Grey Knee-High Kids Trachten Socks",
    productFamily: "kids' Trachten socks",
    visual: "grey textured-knit presentation",
    features: ["Knee-high traditional silhouette", "Decorative knit pattern", "Buyer-specified yarn and sizing"],
    sort: 1429,
    image: "/media/bavarian-drive/assets/children/review-only/shoes-socks-4.webp",
  },
  {
    id: 950031,
    audience: "kids",
    slug: "white-puff-sleeve-kids-dirndl-blouse",
    name: "White Puff-Sleeve Kids Dirndl Blouse",
    productFamily: "kids' Dirndl blouse",
    visual: "clean white presentation",
    features: ["Short puff sleeves", "Rounded neckline", "Cropped elasticated construction"],
    sort: 1430,
    image: "/media/bavarian-drive/assets/children/children-s-dirndl/dirndl-blouses.webp",
  },
  {
    id: 950032,
    audience: "kids",
    slug: "white-lace-puff-kids-dirndl-blouse",
    name: "White Lace-Puff Kids Dirndl Blouse",
    productFamily: "kids' Dirndl blouse",
    visual: "white presentation with lace detail",
    features: ["Short puff sleeves", "Decorative lace edging", "Cropped elasticated construction"],
    sort: 1431,
    image: "/media/bavarian-drive/assets/children/children-s-dirndl/dirndl-blouses-2.webp",
  },
];

function createProduct(product: ProductSeed, categoryId: string): DbProduct {
  return {
    id: `00000000-0000-0000-0000-${String(product.id).padStart(12, "0")}`,
    category_id: categoryId,
    slug: product.slug,
    name: product.name,
    description: `${product.name} in a ${product.visual} with ${product.features.join(", ").toLowerCase()}, prepared for wholesale, OEM and private-label ${product.productFamily} programs. Final materials, colours, sizing and construction are confirmed against the buyer brief.`,
    image_url: product.image,
    gallery: [product.image],
    specs: [
      `${product.visual[0].toUpperCase()}${product.visual.slice(1)}`,
      ...product.features,
      "Buyer-specified materials, colours, trims and size grading available",
      "Private-label customization available",
    ],
    details: [],
    material_specifications: null,
    seo_title: `${product.name} Manufacturer | Irha Apparels`,
    seo_description: `${product.name} for wholesale, OEM and private-label ${product.productFamily} programs from Irha Apparels, a B2B apparel manufacturer in Sialkot, Pakistan.`,
    sort_order: product.sort,
    is_published: true,
    sku: null,
    is_featured: false,
    short_description: `${product.name} for wholesale, OEM, ODM and private-label buyer programs.`,
    moq_display: null,
    moq_min: null,
    sample_available: null,
    sample_timeline: null,
    production_timeline: null,
    country_of_origin: null,
    primary_material: null,
    fabric_composition: null,
    gsm: null,
    available_sizes: [],
    size_notes: null,
    available_colors: [],
    custom_colors: true,
    customization: {},
    packaging_standard: null,
    packaging_custom: null,
    related_product_ids: [],
  };
}

function resolveAudience(subSlug: string, subName: string): Audience | null {
  const normalizedSubName = normalize(subName);

  if (subSlug === "women" || normalizedSubName.startsWith("women")) return "women";
  if (
    subSlug === "kids" ||
    subSlug === "children" ||
    normalizedSubName.includes("kids") ||
    normalizedSubName.includes("children")
  ) {
    return "kids";
  }
  if (subSlug === "men" || normalizedSubName.startsWith("men")) return "men";

  return null;
}

export function createSupplementalFinalCompletion20260714ProductsForSubcategory(
  topCategorySlug: string,
  subSlug: string,
  subName: string,
  categoryId: string,
): DbProduct[] {
  if (topCategorySlug !== "bavarian-trachten-wear") return [];

  const audience = resolveAudience(subSlug, subName);
  if (!audience) return [];

  return PRODUCTS.filter((product) => product.audience === audience).map((product) =>
    createProduct(product, categoryId),
  );
}
