import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const USER_AGENT = "IrhaApparels-Tumblr-Integration/1.2";
const ACCESS_TOKEN_URL = "https://www.tumblr.com/oauth/access_token";
const OAUTH2_EXCHANGE_URL = "https://api.tumblr.com/v2/oauth2/exchange";
function env(name: string) { return Deno.env.get(name)?.trim() || ""; }
function adminClient() { return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY")); }
function pct(v: string) { return encodeURIComponent(v).replace(/[!'()*]/g, c => `%${c.charCodeAt(0).toString(16).toUpperCase()}`); }
function consumer() { return { key: env("TUMBLR_CLIENT_ID") || env("TUMBLR_CONSUMER_KEY"), secret: env("TUMBLR_CLIENT_SECRET") || env("TUMBLR_CONSUMER_SECRET") }; }
function oauthBaseParams(key: string) { return { oauth_consumer_key: key, oauth_nonce: crypto.randomUUID().replaceAll("-", ""), oauth_signature_method: "HMAC-SHA1", oauth_timestamp: String(Math.floor(Date.now()/1000)), oauth_version: "1.0" }; }
async function hmacSha1Base64(key: string, data: string) { const enc=new TextEncoder(); const k=await crypto.subtle.importKey("raw",enc.encode(key),{name:"HMAC",hash:"SHA-1"},false,["sign"]); const sig=new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(data))); let bin=""; for(const b of sig) bin+=String.fromCharCode(b); return btoa(bin); }
async function oauthHeader(method:string,url:string,oauth:Record<string,string>,consumerSecret:string,tokenSecret=""){const pairs=Object.entries(oauth).map(([k,v])=>[pct(k),pct(v)] as [string,string]).sort((a,b)=>a[0]===b[0]?a[1].localeCompare(b[1]):a[0].localeCompare(b[0]));const normalized=pairs.map(([k,v])=>`${k}=${v}`).join("&");const base=`${method.toUpperCase()}&${pct(url)}&${pct(normalized)}`;const signature=await hmacSha1Base64(`${pct(consumerSecret)}&${pct(tokenSecret)}`,base);return "OAuth "+Object.entries({...oauth,oauth_signature:signature}).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${pct(k)}="${pct(v)}"`).join(", ")}
async function parseOAuthResponse(r:Response){const text=await r.text();const p=new URLSearchParams(text);return{ok:r.ok,status:r.status,token:p.get("oauth_token")||"",secret:p.get("oauth_token_secret")||""}}
type TumblrTokenPayload={access_token:string;refresh_token?:string;token_type?:string;scope?:string;expires_in?:number|string};
async function saveCredential(tokens:TumblrTokenPayload){const expiresAt=tokens.expires_in?new Date(Date.now()+Number(tokens.expires_in)*1000).toISOString():null;const{error}=await adminClient().rpc("tumblr_store_tokens",{p_access_token:tokens.access_token,p_refresh_token:tokens.refresh_token||"",p_token_type:tokens.token_type||"bearer",p_scope:tokens.scope||"basic write offline_access",p_expires_at:expiresAt});if(error)throw error}
Deno.serve(async(req:Request)=>{const url=new URL(req.url);const oauthToken=url.searchParams.get("oauth_token")||"";const verifier=url.searchParams.get("oauth_verifier")||"";if(!oauthToken||!verifier)return new Response("Tumblr authorization was not completed.",{status:400});const{data:temp}=await adminClient().from("tumblr_oauth1_temp_tokens").select("oauth_token,token_secret,expires_at,used_at").eq("oauth_token",oauthToken).maybeSingle();if(!temp||temp.used_at||new Date(temp.expires_at).getTime()<Date.now())return new Response("Tumblr authorization session is invalid or expired. Please start again.",{status:400});const c=consumer();if(!c.key||!c.secret)return new Response("Tumblr credentials are not configured.",{status:503});try{const accessOauth={...oauthBaseParams(c.key),oauth_token:oauthToken,oauth_verifier:verifier};const accessAuth=await oauthHeader("POST",ACCESS_TOKEN_URL,accessOauth,c.secret,temp.token_secret);const accessResp=await fetch(ACCESS_TOKEN_URL,{method:"POST",headers:{Authorization:accessAuth,"User-Agent":USER_AGENT}});const access=await parseOAuthResponse(accessResp);if(!access.ok||!access.token||!access.secret)throw new Error(`OAuth1 access-token exchange failed (${access.status})`);const exchangeOauth={...oauthBaseParams(c.key),oauth_token:access.token};const exchangeAuth=await oauthHeader("POST",OAUTH2_EXCHANGE_URL,exchangeOauth,c.secret,access.secret);const exchangeResp=await fetch(OAUTH2_EXCHANGE_URL,{method:"POST",headers:{Authorization:exchangeAuth,Accept:"application/json","User-Agent":USER_AGENT}});const tokens=await exchangeResp.json().catch(()=>({}));if(!exchangeResp.ok||!tokens.access_token)throw new Error(`OAuth1 to OAuth2 exchange failed (${exchangeResp.status})`);await saveCredential(tokens);await adminClient().from("tumblr_oauth1_temp_tokens").delete().eq("oauth_token",oauthToken);return new Response("Tumblr connected to Irha Apparels successfully. You may close this tab and return to ChatGPT.",{status:200,headers:{"Content-Type":"text/plain; charset=utf-8"}})}catch(e){console.error("Tumblr OAuth callback failed",(e as Error).message);return new Response(`Tumblr connection failed: ${(e as Error).message}`,{status:502,headers:{"Content-Type":"text/plain; charset=utf-8"}})}});