// Adapts the committed Lovable catalog tree into the shape used by public pages.
// Legacy auto-generated copy is treated as unverified and is replaced with
// neutral B2B wording before it can reach buyers or search engines.

import { usePublicCatalogTree, type PublicTopCategory } from "@/hooks/usePublicCatalog";
import type { DbProduct } from "@/hooks/useCatalog";
import { CATEGORIES, type Category as LegacyCategory, type Product as LegacyProduct } from "@/lib/categories";
import { CATALOG, type CategoryGroup as LegacyGroup, type SubCategory as LegacySub } from "@/lib/catalog";
import { canonicalCategoryMedia } from "@/lib/categoryMediaRegistry";
import { selectAuthoritativeProductGallery } from "@/lib/productGalleryAuthority";
import { thumbnailUrl } from "@/lib/imageThumbnails";
import { keywordLedProductName } from "@/lib/catalogSearchNames";

export type NormalizedProduct = LegacyProduct & {
  id?: string;
  slug: string;
  sku?: string | null;
  created_at?: string;
  originalImage?: string;
};

export type NormalizedSub = {
  slug: string;
  name: string;
  short: string;
  products: NormalizedProduct[];
};

export type NormalizedCategory = {
  slug: string;
  name: string;
  short: string;
  description: string;
  image: string;
  originalImage: string;
  details: string[];
  subs: NormalizedSub[];
  productCount: number;
  seoTitle?: string;
  seoDescription?: string;
};

const SAFE_LEGACY_SPECS = [
  "Wholesale, OEM and private-label programs",
  "Custom branding, trims and packaging by buyer specification",
  "Material and construction confirmed against the approved sample",
];

const CANONICAL_CATALOG_PRODUCT_MEDIA = /\/storage\/v1\/object\/public\/site-media\/catalog\/products\//i;

function cardImageUrl(source: string): string {
  // Canonical Drive catalogue imports currently store approved WebP originals,
  // but do not have a generated thumbnails/responsive tree. Rewriting these
  // URLs creates nonexistent `.webp.webp` objects and breaks every product card.
  return CANONICAL_CATALOG_PRODUCT_MEDIA.test(source) ? source : thumbnailUrl(source);
}

function safeLegacyDescription(productName: string): string {
  return `${productName} for wholesale, OEM and private-label buyer programs. Material, construction, sizing, branding, packaging, sampling and production details are confirmed against the approved buyer specification.`;
}

function adaptProduct(p: DbProduct): NormalizedProduct {
  const baseGallery = p.gallery?.length ? p.gallery : p.image_url ? [p.image_url] : [];
  const gallery = selectAuthoritativeProductGallery(p.slug, baseGallery);
  const heroImage = gallery[0] ?? p.image_url ?? "";
  const isAutoGeneratedLegacyProduct = p.id.startsWith("local-product-");
  const productName = keywordLedProductName(p.slug, p.name);

  return {
    id: p.id,
    slug: p.slug,
    sku: p.sku ?? null,
    name: productName,
    image: cardImageUrl(heroImage),
    originalImage: heroImage,
    gallery,
    description: isAutoGeneratedLegacyProduct
      ? safeLegacyDescription(productName)
      : p.description ?? safeLegacyDescription(productName),
    specs: isAutoGeneratedLegacyProduct ? SAFE_LEGACY_SPECS : p.specs ?? [],
    details: isAutoGeneratedLegacyProduct
      ? []
      : Array.isArray(p.details)
        ? p.details
        : [],
    created_at: p.created_at,
  };
}

function adaptTop(top: PublicTopCategory): NormalizedCategory {
  const subs: NormalizedSub[] = top.subs.map((s) => ({
    slug: s.slug,
    name: s.name,
    short: s.short ?? "",
    products: s.products.map(adaptProduct),
  }));
  const registeredMedia = canonicalCategoryMedia(top.slug);
  const originalImage = registeredMedia?.src ?? top.image_url ?? "";
  return {
    slug: top.slug,
    name: top.name,
    short: top.short ?? "",
    description: top.description ?? "",
    image: registeredMedia?.src ?? thumbnailUrl(originalImage),
    originalImage,
    details: [],
    subs,
    productCount: subs.reduce((n, s) => n + s.products.length, 0),
    seoTitle: top.seo_title ?? undefined,
    seoDescription: top.seo_description ?? undefined,
  };
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function legacyAdaptProduct(product: LegacyProduct): NormalizedProduct {
  const slug = slugify(product.name);
  const productName = keywordLedProductName(slug, product.name);
  const baseGallery = product.gallery?.length ? product.gallery : product.image ? [product.image] : [];
  const gallery = selectAuthoritativeProductGallery(slug, baseGallery);
  const heroImage = gallery[0] ?? product.image;

  return {
    ...product,
    slug,
    name: productName,
    image: thumbnailUrl(heroImage),
    originalImage: heroImage,
    gallery,
    description: safeLegacyDescription(productName),
    specs: SAFE_LEGACY_SPECS,
    details: [],
  };
}

function legacyAdaptGroup(cat: LegacyCategory, group: LegacyGroup | undefined): NormalizedCategory {
  const subs: NormalizedSub[] = (group?.subs ?? []).map((s: LegacySub) => ({
    slug: s.slug,
    name: s.name,
    short: s.short,
    products: s.products.map(legacyAdaptProduct),
  }));
  const registeredMedia = canonicalCategoryMedia(cat.slug);
  const originalImage = registeredMedia?.src ?? cat.image;
  return {
    slug: cat.slug,
    name: cat.name,
    short: cat.short,
    description: cat.short,
    image: registeredMedia?.src ?? thumbnailUrl(originalImage),
    originalImage,
    details: [],
    subs,
    productCount: subs.reduce((n, s) => n + s.products.length, 0),
  };
}

export function usePublicCategories() {
  const q = usePublicCatalogTree();
  if (q.data) {
    return {
      isLoading: q.isLoading,
      isError: false as const,
      source: "local" as const,
      categories: q.data.filter((t) => t.is_published).map(adaptTop),
    };
  }
  if (q.isError) {
    const cats = CATEGORIES.map((c) => legacyAdaptGroup(c, CATALOG.find((g) => g.slug === c.slug)));
    return { isLoading: false, isError: true as const, source: "legacy" as const, categories: cats };
  }
  return { isLoading: q.isLoading, isError: false as const, source: "local" as const, categories: [] as NormalizedCategory[] };
}

export function useNormalizedCategory(slug?: string) {
  const { categories, isLoading, source, isError } = usePublicCategories();
  const category = slug ? categories.find((c) => c.slug === slug) ?? null : null;
  return { category, isLoading, source, isError };
}
