import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const OAUTH1_REQUEST_TOKEN_URL="https://www.tumblr.com/oauth/request_token";
const OAUTH1_AUTHORIZE_URL="https://www.tumblr.com/oauth/authorize";
const TUMBLR_AUTH_URL="https://www.tumblr.com/oauth2/authorize";
const TUMBLR_TOKEN_URL="https://api.tumblr.com/v2/oauth2/token";
const TUMBLR_API="https://api.tumblr.com/v2";
const USER_AGENT="IrhaApparels-Tumblr-Integration/1.3";

type OperatorJob={id:string;action:string;payload:Record<string,unknown>;expires_at:string;status:string;used_at:string|null};

function json(payload:unknown,status=200){return new Response(JSON.stringify(payload),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function env(name:string){return Deno.env.get(name)?.trim()||""}
function adminClient(){return createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}})}
function config(){return{clientId:env("TUMBLR_CLIENT_ID")||env("TUMBLR_CONSUMER_KEY"),clientSecret:env("TUMBLR_CLIENT_SECRET")||env("TUMBLR_CONSUMER_SECRET"),redirectUri:env("TUMBLR_REDIRECT_URI")||`${env("SUPABASE_URL")}/functions/v1/tumblr-operator?action=callback`,oauth1Callback:`${env("SUPABASE_URL")}/functions/v1/tumblr-oauth-callback`}}
function pct(v:string){return encodeURIComponent(v).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`)}
function oauthBaseParams(key:string){return{oauth_consumer_key:key,oauth_nonce:crypto.randomUUID().replaceAll("-",""),oauth_signature_method:"HMAC-SHA1",oauth_timestamp:String(Math.floor(Date.now()/1000)),oauth_version:"1.0"}}
async function hmacSha1Base64(key:string,data:string){const enc=new TextEncoder();const k=await crypto.subtle.importKey("raw",enc.encode(key),{name:"HMAC",hash:"SHA-1"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(data)));let bin="";for(const b of sig)bin+=String.fromCharCode(b);return btoa(bin)}
async function oauthHeader(method:string,url:string,oauth:Record<string,string>,consumerSecret:string,tokenSecret=""){const pairs=Object.entries(oauth).map(([k,v])=>[pct(k),pct(v)] as [string,string]).sort((a,b)=>a[0]===b[0]?a[1].localeCompare(b[1]):a[0].localeCompare(b[0]));const normalized=pairs.map(([k,v])=>`${k}=${v}`).join("&");const base=`${method.toUpperCase()}&${pct(url)}&${pct(normalized)}`;const signature=await hmacSha1Base64(`${pct(consumerSecret)}&${pct(tokenSecret)}`,base);return"OAuth "+Object.entries({...oauth,oauth_signature:signature}).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${pct(k)}="${pct(v)}"`).join(", ")}
async function sha256Hex(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function requireAdmin(req:Request){const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const client=createClient(env("SUPABASE_URL"),env("SUPABASE_ANON_KEY"),{global:{headers:{Authorization:`Bearer ${token}`}}});const {data:userData}=await client.auth.getUser(token);const user=userData?.user;if(!user)return null;const {data:role}=await client.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();return role?user:null}
function authorizationUrl(clientId:string,redirectUri:string,state:string,includeRedirect=true){const u=new URL(TUMBLR_AUTH_URL);const p:Record<string,string>={client_id:clientId,response_type:"code",scope:"basic write offline_access",state};if(includeRedirect)p.redirect_uri=redirectUri;u.search=new URLSearchParams(p).toString();return u.toString()}
async function oauth1RequestToken(cfg:ReturnType<typeof config>){const oauth={...oauthBaseParams(cfg.clientId),oauth_callback:cfg.oauth1Callback};const auth=await oauthHeader("POST",OAUTH1_REQUEST_TOKEN_URL,oauth,cfg.clientSecret);const r=await fetch(OAUTH1_REQUEST_TOKEN_URL,{method:"POST",headers:{Authorization:auth,"User-Agent":USER_AGENT}});const text=await r.text();const p=new URLSearchParams(text);if(!r.ok||!p.get("oauth_token")||!p.get("oauth_token_secret"))throw new Error(`tumblr_oauth1_request_failed:${r.status}`);return{token:p.get("oauth_token")!,secret:p.get("oauth_token_secret")!}}
async function tokenRequest(params:Record<string,string>){const{clientId,clientSecret}=config();const r=await fetch(TUMBLR_TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json","User-Agent":USER_AGENT},body:new URLSearchParams({...params,client_id:clientId,client_secret:clientSecret})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`tumblr_refresh_failed:${r.status}`);return body}
async function getCredential(){const{data,error}=await adminClient().rpc("tumblr_get_tokens");if(error)throw error;return Array.isArray(data)?data[0]??null:data}
type TumblrTokenPayload={access_token:string;refresh_token?:string;token_type?:string;scope?:string;expires_in?:number|string};
async function saveCredential(tokens:TumblrTokenPayload){const expiresAt=tokens.expires_in?new Date(Date.now()+Number(tokens.expires_in)*1000).toISOString():null;const{error}=await adminClient().rpc("tumblr_store_tokens",{p_access_token:tokens.access_token,p_refresh_token:tokens.refresh_token||"",p_token_type:tokens.token_type||"bearer",p_scope:tokens.scope||"write offline_access basic",p_expires_at:expiresAt});if(error)throw error}
async function accessToken(){const cred=await getCredential();if(!cred)throw new Error("tumblr_not_connected");const stillValid=cred.expires_at&&new Date(cred.expires_at).getTime()>Date.now()+120000;if(stillValid&&cred.access_token)return cred.access_token as string;if(!cred.refresh_token)throw new Error("tumblr_refresh_token_missing");const refreshed=await tokenRequest({grant_type:"refresh_token",refresh_token:cred.refresh_token});await saveCredential(refreshed);return refreshed.access_token as string}
async function tumblrFetch(path:string,init:RequestInit={}){const token=await accessToken();const r=await fetch(`${TUMBLR_API}${path}`,{...init,headers:{...(init.headers||{}),Authorization:`Bearer ${token}`,"User-Agent":USER_AGENT}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`tumblr_api_failed:${r.status}`);return body}

async function inventory(){const me=await tumblrFetch("/user/info");const user=me?.response?.user||{};const blogs=(Array.isArray(user.blogs)?user.blogs:[]) as Array<{name?:string;title?:string;uuid?:string;url?:string;primary?:boolean}>;const primary=blogs.find((b)=>b.primary)||blogs[0]||null;return{verified:true,user_name:user.name||null,primary_blog:primary?{name:primary.name||null,title:primary.title||null,uuid:primary.uuid||null,url:primary.url||null}:null,blogs:blogs.map((b)=>({name:b.name||null,title:b.title||null,uuid:b.uuid||null,url:b.url||null,primary:Boolean(b.primary)}))}}
async function publish(payload:Record<string,unknown>){const blog=String(payload.blog||env("TUMBLR_BLOG_IDENTIFIER")||"").trim();if(!blog)throw new Error("tumblr_blog_required");const content=Array.isArray(payload.content)?payload.content:[];if(content.length===0)throw new Error("tumblr_content_required");const requested=String(payload.state||"draft");const state=requested==="queue"?"queue":requested==="published"?"published":"draft";if(state==="published"&&payload.confirm_publish!==true)throw new Error("tumblr_publish_confirmation_required");const body:Record<string,unknown>={content,state};if(Array.isArray(payload.tags))body.tags=payload.tags.slice(0,30).map(String);if(Array.isArray(payload.layout))body.layout=payload.layout;const result=await tumblrFetch(`/blog/${encodeURIComponent(blog)}/posts`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(body)});return{blog,state,response:result.response||result}}
function sanitizeError(message:string){for(const prefix of ["tumblr_api_failed:","tumblr_refresh_failed:"])if(message.startsWith(prefix))return message;const allowed=["tumblr_not_connected","tumblr_refresh_token_missing","tumblr_blog_required","tumblr_content_required","tumblr_publish_confirmation_required","unsupported_action"];return allowed.includes(message)?message:"tumblr_operation_failed"}
async function processOperatorJob(operatorToken:string){if(!/^[A-Za-z0-9_-]{40,120}$/.test(operatorToken))return json({error:"forbidden"},403);const service=adminClient();const tokenHash=await sha256Hex(operatorToken);const{data:row,error:readError}=await service.from("tumblr_operator_jobs").select("id,action,payload,expires_at,status,used_at").eq("token_hash",tokenHash).maybeSingle();if(readError||!row)return json({error:"forbidden"},403);const job=row as OperatorJob;if(job.status!=="pending"||job.used_at)return json({error:"job_not_available"},409);if(new Date(job.expires_at).getTime()<=Date.now()){await service.from("tumblr_operator_jobs").update({status:"expired",finished_at:new Date().toISOString()}).eq("id",job.id).eq("status","pending");return json({error:"job_expired"},410)}const now=new Date().toISOString();const{data:claimed,error:claimError}=await service.from("tumblr_operator_jobs").update({status:"running",used_at:now,started_at:now}).eq("id",job.id).eq("status","pending").is("used_at",null).select("id").maybeSingle();if(claimError||!claimed)return json({error:"job_not_available"},409);try{let result:Record<string,unknown>;if(job.action==="inventory")result=await inventory();else if(job.action==="publish")result=await publish(job.payload||{});else throw new Error("unsupported_action");await service.from("tumblr_operator_jobs").update({status:"succeeded",result,finished_at:new Date().toISOString(),error_code:null}).eq("id",job.id);return json({ok:true,job_id:job.id,action:job.action,result})}catch(e){const code=sanitizeError(e instanceof Error?e.message:"tumblr_operation_failed");await service.from("tumblr_operator_jobs").update({status:"failed",error_code:code,finished_at:new Date().toISOString()}).eq("id",job.id);console.error("tumblr_operator_job_failed",code);return json({ok:false,job_id:job.id,error:code},500)}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});const url=new URL(req.url),explicitAction=url.searchParams.get("action"),action=explicitAction||"probe",cfg=config();
if(req.method==="POST"&&!explicitAction){const body=await req.json().catch(()=>({}));if(typeof body?.token==="string")return processOperatorJob(body.token);return json({error:"operator_token_required"},400)}
if(action==="probe"){let connected=false;try{connected=Boolean(await getCredential())}catch{/* credential lookup failure means disconnected */}return json({configured:Boolean(cfg.clientId&&cfg.clientSecret),connected,authorization_mode:"oauth1_to_oauth2",oauth1_callback:cfg.oauth1Callback,redirect_uri:cfg.redirectUri})}
if(action==="bootstrap"){if(!cfg.clientId||!cfg.clientSecret)return json({error:"Tumblr client credentials are not configured"},503);const token=url.searchParams.get("token")||"";if(token.length<32)return json({error:"Invalid bootstrap token"},403);const tokenHash=await sha256Hex(token);const{data:bootstrap,error:readError}=await adminClient().from("tumblr_oauth_bootstrap_tokens").select("token_hash,expires_at,use_count,max_uses").eq("token_hash",tokenHash).maybeSingle();if(readError)return json({error:"Authorization link storage is not ready"},503);if(!bootstrap||new Date(bootstrap.expires_at).getTime()<Date.now())return json({error:"Bootstrap link is invalid or expired"},403);const maxUses=Number(bootstrap.max_uses||1),useCount=Number(bootstrap.use_count||0);if(useCount>=maxUses)return json({error:"Bootstrap link usage limit reached"},403);try{const temp=await oauth1RequestToken(cfg);const expiresAt=new Date(Date.now()+15*60*1000).toISOString();const{error:tempError}=await adminClient().from("tumblr_oauth1_temp_tokens").upsert({oauth_token:temp.token,token_secret:temp.secret,expires_at:expiresAt,used_at:null},{onConflict:"oauth_token"});if(tempError)throw tempError;const{error:countError}=await adminClient().from("tumblr_oauth_bootstrap_tokens").update({use_count:useCount+1,used_at:useCount+1>=maxUses?new Date().toISOString():null}).eq("token_hash",tokenHash).eq("use_count",useCount);if(countError){await adminClient().from("tumblr_oauth1_temp_tokens").delete().eq("oauth_token",temp.token);throw countError}const auth=new URL(OAUTH1_AUTHORIZE_URL);auth.searchParams.set("oauth_token",temp.token);return Response.redirect(auth.toString(),302)}catch(e){console.error("Tumblr OAuth1 bootstrap failed",(e as Error).message);return json({error:(e as Error).message},502)}}
if(action==="callback"){const code=url.searchParams.get("code")||"",state=url.searchParams.get("state")||"";const{data:stateRow}=await adminClient().from("tumblr_oauth_states").select("state,expires_at,used_at").eq("state",state).maybeSingle();if(!code||!stateRow||stateRow.used_at||new Date(stateRow.expires_at).getTime()<Date.now())return json({error:"Invalid or expired OAuth state"},400);const params:Record<string,string>={grant_type:"authorization_code",code};if(!state.startsWith("nr_"))params.redirect_uri=cfg.redirectUri;const tokens=await tokenRequest(params);await saveCredential(tokens);await adminClient().from("tumblr_oauth_states").update({used_at:new Date().toISOString()}).eq("state",state);return new Response("Tumblr connected to Irha Apparels. You may close this tab.",{status:200,headers:{"Content-Type":"text/plain; charset=utf-8"}})}
const admin=await requireAdmin(req);if(!admin)return json({error:"Forbidden — admin only"},403);
if(action==="start"){if(!cfg.clientId||!cfg.clientSecret)return json({error:"Tumblr client credentials are not configured"},503);const state=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");const expiresAt=new Date(Date.now()+10*60*1000).toISOString();const{error}=await adminClient().from("tumblr_oauth_states").insert({state,expires_at:expiresAt,created_by:admin.id});if(error)return json({error:error.message},500);return json({authorize_url:authorizationUrl(cfg.clientId,cfg.redirectUri,state,true),expires_at:expiresAt,redirect_uri:cfg.redirectUri})}
if(action==="health"){try{return json({configured:true,connected:true,...await inventory(),authorization_mode:"oauth1_to_oauth2"})}catch(e){return json({configured:Boolean(cfg.clientId&&cfg.clientSecret),connected:Boolean(await getCredential().catch(()=>null)),verified:false,error:sanitizeError((e as Error).message)},502)}}
if(action==="publish"){if(req.method!=="POST")return json({error:"POST required"},405);const body=await req.json().catch(()=>({}));try{return json({success:true,...await publish(body)})}catch(e){return json({success:false,error:sanitizeError((e as Error).message)},400)}}
return json({error:"Unknown action"},400)});