import { FAMILIES, FAMILY_NODES, ALL_SLOTS, MAIN_CATEGORIES } from "/dev-server/src/lib/catalogTaxonomyManifest";
import { createHash } from "node:crypto";

function uuid(seed: string): string {
  const h = createHash("sha1").update("irha:taxo:" + seed).digest("hex");
  return `${h.substr(0,8)}-${h.substr(8,4)}-5${h.substr(13,3)}-8${h.substr(17,3)}-${h.substr(20,12)}`;
}
function q(s: string) { return "'" + s.replace(/'/g, "''") + "'"; }

const lines: string[] = [];
lines.push("-- Auto-generated by scripts/emit-taxonomy-seed.ts from src/lib/catalogTaxonomyManifest.ts.");
lines.push("-- 5 mains + audience nodes + 103 families + 206 planned product slots.");
lines.push("-- All slots ship draft/unpublished/missing-media. No fake public content.");
lines.push("begin;");
lines.push("");

// 1. main_category nodes
for (const m of MAIN_CATEGORIES) {
  const id = uuid(`main:${m.slug}`);
  lines.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) values (${q(id)}, null, 'main_category', ${q(m.slug)}, ${q(m.name)}, 0, ${q(m.slug)}, 0, 'draft') on conflict (full_slug_path) do nothing;`);
}
lines.push("");

// 2. audience nodes (unique per main+audience)
const audienceIds = new Map<string, string>();
const seenAud = new Set<string>();
let audSort = 0;
for (const f of FAMILIES) {
  const key = `${f.main}/${f.audience}`;
  if (seenAud.has(key)) continue;
  seenAud.add(key);
  const parentId = uuid(`main:${f.main}`);
  const id = uuid(`aud:${key}`);
  audienceIds.set(key, id);
  const audName = f.audience.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
  lines.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) values (${q(id)}, ${q(parentId)}, 'audience', ${q(f.audience)}, ${q(audName)}, 1, ${q(key)}, ${audSort++}, 'draft') on conflict (full_slug_path) do nothing;`);
}
lines.push("");

// 3. product_type (family) nodes
let famSort = 0;
for (const fn of FAMILY_NODES) {
  const audKey = `${fn.main}/${fn.audience}`;
  const parentId = audienceIds.get(audKey)!;
  const id = uuid(`fam:${fn.fullSlugPath}`);
  lines.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) values (${q(id)}, ${q(parentId)}, 'product_type', ${q(fn.slug)}, ${q(fn.name)}, 2, ${q(fn.fullSlugPath)}, ${famSort++}, 'draft') on conflict (full_slug_path) do nothing;`);
}
lines.push("");

// 4. category rows (products.category_id FK). Reuse existing categories rows by slug (already 5 mains present).
lines.push("-- Products link to public.categories via category_id. Resolve each main slug at insert time.");
lines.push("");

// 5. product slots
let slotSort = 0;
for (const s of ALL_SLOTS) {
  const id = uuid(`slot:${s.referenceCode}`);
  const desc = `Planned catalogue slot for ${s.familyName}. Draft record: not for public rendering until owner approval, verified specifications, approved media and taxonomy sign-off are in place.`;
  lines.push(`insert into public.products (id, category_id, slug, name, description, sku, is_published, is_featured, sort_order, gallery, specs, details, available_sizes, available_colors, customization, related_product_ids) select ${q(id)}, c.id, ${q(s.slug)}, ${q(s.workingTitle)}, ${q(desc)}, ${q(s.referenceCode)}, false, false, ${slotSort++}, '{}'::text[], '{}'::text[], '{}'::jsonb, '{}'::text[], '{}'::text[], '{}'::jsonb, '{}'::uuid[] from public.categories c where c.slug = ${q(s.main)} on conflict (id) do nothing;`);
}
lines.push("");

// 6. product_taxonomy_assignments
for (const s of ALL_SLOTS) {
  const productId = uuid(`slot:${s.referenceCode}`);
  const familyPath = `${s.main}/${s.audience}/${s.familySlug}`;
  const familyNodeId = uuid(`fam:${familyPath}`);
  lines.push(`insert into public.product_taxonomy_assignments (product_id, taxonomy_node_id, assignment_source, review_state) values (${q(productId)}, ${q(familyNodeId)}, 'migration', 'proposed') on conflict (product_id) do nothing;`);
}
lines.push("");
lines.push("commit;");

import { writeFileSync } from "node:fs";
writeFileSync("/dev-server/supabase/migrations/20260718000000_seed_planned_taxonomy_206_slots.sql", lines.join("\n") + "\n");
console.log("wrote", lines.length, "lines");
