// Deterministic emitter: builds a seed migration from
// src/lib/catalogTaxonomyManifest.ts. Idempotent (ON CONFLICT DO NOTHING).
// Node UUIDs match the existing foundation migration convention
// md5('irha-taxonomy:' || full_slug_path) so re-runs merge cleanly.
import { FAMILIES, FAMILY_NODES, ALL_SLOTS, MAIN_CATEGORIES } from "/dev-server/src/lib/catalogTaxonomyManifest";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";

function nodeUuid(fullPath: string): string {
  const h = createHash("md5").update("irha-taxonomy:" + fullPath).digest("hex");
  return `${h.substr(0,8)}-${h.substr(8,4)}-${h.substr(12,4)}-${h.substr(16,4)}-${h.substr(20,12)}`;
}
function slotUuid(ref: string): string {
  const h = createHash("md5").update("irha-slot:" + ref).digest("hex");
  return `${h.substr(0,8)}-${h.substr(8,4)}-${h.substr(12,4)}-${h.substr(16,4)}-${h.substr(20,12)}`;
}
function q(s: string) { return "'" + s.replace(/'/g, "''") + "'"; }

const L: string[] = [];
L.push("-- Auto-generated by scripts/emit-taxonomy-seed.ts.");
L.push("-- Source of truth: src/lib/catalogTaxonomyManifest.ts.");
L.push("-- Seeds 5 mains + audience nodes + 103 families + 206 planned product slots.");
L.push("-- All slots ship draft/unpublished, no media, no public rendering.");
L.push("begin;");
L.push("");
L.push("-- Ensure 5 main_category nodes exist (idempotent with foundation migration).");
for (const m of MAIN_CATEGORIES) {
  const id = nodeUuid(m.slug);
  L.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) values (${q(id)}, null, 'main_category', ${q(m.slug)}, ${q(m.name)}, 0, ${q(m.slug)}, 0, 'draft') on conflict (full_slug_path) do nothing;`);
}
L.push("");
L.push("-- Audience group nodes (depth 1) under each main.");
const seenAud = new Set<string>();
let audSort = 0;
for (const f of FAMILIES) {
  const key = `${f.main}/${f.audience}`;
  if (seenAud.has(key)) continue;
  seenAud.add(key);
  const id = nodeUuid(key);
  const audName = f.audience === "team-club" ? "Teams & Clubs" : f.audience === "family-hospitality" ? "Family & Hospitality" : f.audience.replace(/\b\w/g, c => c.toUpperCase());
  L.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) select ${q(id)}, p.id, 'audience', ${q(f.audience)}, ${q(audName)}, 1, ${q(key)}, ${audSort++}, 'draft' from public.catalog_taxonomy_nodes p where p.full_slug_path = ${q(f.main)} on conflict (full_slug_path) do nothing;`);
}
L.push("");
L.push("-- Product-type (family) nodes (depth 2 — leaf).");
let famSort = 0;
for (const fn of FAMILY_NODES) {
  const parentKey = `${fn.main}/${fn.audience}`;
  const id = nodeUuid(fn.fullSlugPath);
  L.push(`insert into public.catalog_taxonomy_nodes (id, parent_id, node_type, slug, name, depth, full_slug_path, sort_order, publish_state) select ${q(id)}, p.id, 'product_type', ${q(fn.slug)}, ${q(fn.name)}, 2, ${q(fn.fullSlugPath)}, ${famSort++}, 'draft' from public.catalog_taxonomy_nodes p where p.full_slug_path = ${q(parentKey)} on conflict (full_slug_path) do nothing;`);
}
L.push("");
L.push("-- 206 planned product slots. Every row is draft, unpublished, no media,");
L.push("-- with a stable reference code and canonical path. No fake public content.");
let slotSort = 0;
for (const s of ALL_SLOTS) {
  const id = slotUuid(s.referenceCode);
  const desc = `Planned catalogue slot for ${s.familyName}. Draft record: not for public rendering until owner approval, verified specifications, approved media and taxonomy sign-off are in place.`;
  L.push(`insert into public.products (id, category_id, slug, name, description, sku, is_published, is_featured, sort_order, gallery, specs, details, available_sizes, available_colors, customization, related_product_ids) select ${q(id)}, c.id, ${q(s.slug)}, ${q(s.workingTitle)}, ${q(desc)}, ${q(s.referenceCode)}, false, false, ${slotSort++}, '{}'::text[], '{}'::text[], '{}'::jsonb, '{}'::text[], '{}'::text[], '{}'::jsonb, '{}'::uuid[] from public.categories c where c.slug = ${q(s.main)} on conflict (id) do nothing;`);
}
L.push("");
L.push("-- Link every product to its product-type node as a proposed taxonomy assignment.");
for (const s of ALL_SLOTS) {
  const pid = slotUuid(s.referenceCode);
  const familyPath = `${s.main}/${s.audience}/${s.familySlug}`;
  const nid = nodeUuid(familyPath);
  L.push(`insert into public.product_taxonomy_assignments (product_id, taxonomy_node_id, assignment_source, review_state) values (${q(pid)}, ${q(nid)}, 'migration', 'proposed') on conflict (product_id) do nothing;`);
}
L.push("");
L.push("commit;");
writeFileSync("/dev-server/supabase/migrations/20260718000000_seed_planned_taxonomy_206_slots.sql", L.join("\n") + "\n");
console.log("wrote", L.length, "lines");
