// Runs before `vite dev` and `vite build`; writes public/sitemap.xml.
import { writeFileSync } from "fs";
import { resolve } from "path";

const BASE_URL = "https://www.irhaapparels.com";

interface SitemapEntry {
  path: string;
  changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority?: string;
}

const journalSlugs = [
  "craft-of-lederhosen",
  "leather-grades-explained",
  "sialkot-apparel-legacy",
  "streetwear-500gsm",
  "sustainable-cotton-program",
  "moq-economics",
];

const blogSlugs = [
  "why-source-sportswear-from-pakistan",
  "lederhosen-manufacturing-guide",
  "private-label-streetwear-manufacturing",
  "why-sialkot-is-global-apparel-hub",
  "oem-vs-odm-clothing-manufacturing",
];

const seoLandingSlugs = [
  "sportswear-manufacturer-pakistan",
  "sportswear-manufacturer-sialkot",
  "private-label-sportswear-manufacturer",
  "leatherwear-manufacturer-pakistan",
  "leather-jacket-manufacturer",
  "lederhosen-manufacturer",
  "trachten-manufacturer",
  "oktoberfest-clothing-manufacturer",
  "streetwear-manufacturer-pakistan",
  "custom-apparel-manufacturer-pakistan",
  // Country pages
  "germany-apparel-manufacturer",
  "austria-lederhosen-manufacturer",
  "uae-sportswear-manufacturer",
  "usa-private-label-clothing-manufacturer",
  "uk-custom-apparel-manufacturer",
  // 30 location × product pages — leatherwear
  "leather-jacket-manufacturer-new-york",
  "wholesale-leather-gloves-london",
  "custom-leather-pants-berlin",
  "b2b-leather-bags-supplier-sydney",
  "leather-jacket-wholesale-toronto",
  "leather-bags-manufacturer-dubai",
  // Bavarian
  "lederhosen-manufacturer-munich",
  "dirndl-wholesale-supplier-vienna",
  "trachten-jackets-manufacturer-salzburg",
  "oktoberfest-clothing-wholesale-zurich",
  "trachten-manufacturer-stuttgart",
  // Sportswear
  "tracksuit-manufacturer-manchester",
  "custom-team-jerseys-los-angeles",
  "wholesale-leggings-supplier-madrid",
  "gym-wear-oem-dubai",
  "sportswear-manufacturer-amsterdam",
  "sports-bras-manufacturer-melbourne",
  "team-wear-supplier-paris",
  // Streetwear
  "hoodie-manufacturer-tokyo",
  "cargo-pants-supplier-berlin",
  "oversized-tees-wholesale-london",
  "streetwear-manufacturer-new-york",
  "private-label-streetwear-paris",
  "hoodie-wholesale-supplier-toronto",
  // Leisurewear
  "loungewear-manufacturer-copenhagen",
  "robe-manufacturer-milan",
  "casual-sets-supplier-stockholm",
  "loungewear-wholesale-paris",
  "robe-wholesale-supplier-dubai",
  "casual-sets-manufacturer-sydney",
  // 120 additional V2 location × product pages (30 hand-crafted + 90 templated)
  "cargo-pants-manufacturer-melbourne",
  "cargo-pants-manufacturer-milan",
  "cargo-pants-manufacturer-paris",
  "cargo-pants-oem-seoul",
  "cargo-pants-supplier-amsterdam",
  "cargo-pants-supplier-singapore",
  "cargo-pants-supplier-tokyo",
  "cargo-pants-wholesale-dubai",
  "cargo-pants-wholesale-london",
  "casual-sets-manufacturer-frankfurt",
  "casual-sets-manufacturer-london",
  "casual-sets-manufacturer-melbourne",
  "casual-sets-oem-dubai",
  "casual-sets-supplier-amsterdam",
  "casual-sets-supplier-milan",
  "casual-sets-supplier-tokyo",
  "casual-sets-supplier-vienna",
  "casual-sets-wholesale-madrid",
  "casual-sets-wholesale-singapore",
  "dirndl-manufacturer-melbourne",
  "dirndl-manufacturer-zurich",
  "dirndl-supplier-hamburg",
  "dirndl-supplier-vienna",
  "dirndl-wholesale-chicago",
  "gym-wear-manufacturer-london",
  "gym-wear-manufacturer-melbourne",
  "gym-wear-manufacturer-seoul",
  "gym-wear-supplier-paris",
  "gym-wear-supplier-singapore",
  "gym-wear-wholesale-tokyo",
  "hoodie-manufacturer-madrid",
  "hoodie-manufacturer-singapore",
  "hoodie-oem-stockholm",
  "hoodie-supplier-melbourne",
  "hoodie-supplier-paris",
  "hoodie-supplier-seoul",
  "hoodie-wholesale-dubai",
  "hoodie-wholesale-milan",
  "hoodies-wholesale-amsterdam",
  "leather-bags-manufacturer-paris",
  "leather-bags-supplier-hong-kong",
  "leather-bags-supplier-milan",
  "leather-bags-wholesale-frankfurt",
  "leather-bags-wholesale-singapore",
  "leather-gloves-manufacturer-madrid",
  "leather-gloves-oem-dubai",
  "leather-gloves-supplier-milan",
  "leather-gloves-wholesale-paris",
  "leather-gloves-wholesale-stockholm",
  "leather-jacket-manufacturer-los-angeles",
  "leather-jacket-manufacturer-paris",
  "leather-jacket-manufacturer-zurich",
  "leather-jacket-oem-seoul",
  "leather-jacket-supplier-frankfurt",
  "leather-jacket-supplier-tokyo",
  "leather-jacket-wholesale-amsterdam",
  "leather-pants-manufacturer-amsterdam",
  "leather-pants-manufacturer-paris",
  "leather-pants-supplier-tokyo",
  "leather-pants-wholesale-madrid",
  "lederhosen-manufacturer-chicago",
  "lederhosen-manufacturer-frankfurt",
  "lederhosen-supplier-melbourne",
  "lederhosen-supplier-zurich",
  "lederhosen-wholesale-toronto",
  "lederhosen-wholesale-vienna",
  "leggings-manufacturer-dubai",
  "leggings-manufacturer-paris",
  "leggings-manufacturer-stockholm",
  "leggings-oem-seoul",
  "leggings-supplier-london",
  "leggings-wholesale-tokyo",
  "loungewear-manufacturer-chicago",
  "loungewear-manufacturer-los-angeles",
  "loungewear-manufacturer-madrid",
  "loungewear-manufacturer-melbourne",
  "loungewear-oem-seoul",
  "loungewear-supplier-frankfurt",
  "loungewear-supplier-london",
  "loungewear-supplier-singapore",
  "loungewear-supplier-tokyo",
  "loungewear-wholesale-dubai",
  "loungewear-wholesale-milan",
  "oktoberfest-clothing-supplier-brussels",
  "oversized-tees-manufacturer-los-angeles",
  "oversized-tees-manufacturer-melbourne",
  "oversized-tees-manufacturer-paris",
  "oversized-tees-supplier-amsterdam",
  "oversized-tees-supplier-tokyo",
  "oversized-tees-wholesale-chicago",
  "oversized-tees-wholesale-seoul",
  "robes-manufacturer-bangkok",
  "robes-manufacturer-doha",
  "robes-manufacturer-london",
  "robes-manufacturer-zurich",
  "robes-supplier-kuala-lumpur",
  "robes-supplier-paris",
  "robes-supplier-riyadh",
  "robes-supplier-singapore",
  "robes-wholesale-frankfurt",
  "robes-wholesale-melbourne",
  "sports-bras-supplier-amsterdam",
  "sportswear-supplier-singapore",
  "streetwear-supplier-sydney",
  "team-jerseys-manufacturer-melbourne",
  "team-jerseys-manufacturer-milan",
  "team-jerseys-supplier-amsterdam",
  "team-jerseys-supplier-chicago",
  "team-jerseys-supplier-madrid",
  "team-jerseys-wholesale-doha",
  "trachten-jackets-supplier-zurich",
  "trachten-jackets-wholesale-frankfurt",
  "trachten-wholesale-cologne",
  "tracksuit-manufacturer-melbourne",
  "tracksuit-manufacturer-paris",
  "tracksuit-oem-seoul",
  "tracksuit-supplier-milan",
  "tracksuit-supplier-tokyo",
  "tracksuit-wholesale-riyadh",
  "tracksuit-wholesale-singapore",
];

const categorySlugs = ["bavarian", "sportswear", "leatherwear", "streetwear", "leisurewear", "nightwear"];

const entries: SitemapEntry[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.8" },
  { path: "/products", changefreq: "weekly", priority: "0.9" },
  { path: "/manufacturing", changefreq: "monthly", priority: "0.8" },
  { path: "/sustainability", changefreq: "monthly", priority: "0.7" },
  { path: "/journal", changefreq: "weekly", priority: "0.7" },
  { path: "/blog", changefreq: "weekly", priority: "0.8" },
  { path: "/faq", changefreq: "monthly", priority: "0.6" },
  { path: "/inquiry", changefreq: "monthly", priority: "0.8" },
  { path: "/contact", changefreq: "monthly", priority: "0.6" },
  { path: "/privacy-policy", changefreq: "yearly", priority: "0.3" },
  ...seoLandingSlugs.map((slug) => ({ path: `/${slug}`, changefreq: "weekly" as const, priority: "0.95" })),
  ...categorySlugs.map((slug) => ({ path: `/products/${slug}`, changefreq: "weekly" as const, priority: "0.85" })),
  ...blogSlugs.map((slug) => ({ path: `/blog/${slug}`, changefreq: "monthly" as const, priority: "0.7" })),
  ...journalSlugs.map((slug) => ({ path: `/journal/${slug}`, changefreq: "monthly" as const, priority: "0.6" })),
];

const today = new Date().toISOString().slice(0, 10);

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
  ...entries.map((e) =>
    [
      `  <url>`,
      `    <loc>${BASE_URL}${e.path}</loc>`,
      `    <lastmod>${today}</lastmod>`,
      e.changefreq ? `    <changefreq>${e.changefreq}</changefreq>` : null,
      e.priority ? `    <priority>${e.priority}</priority>` : null,
      `  </url>`,
    ]
      .filter(Boolean)
      .join("\n"),
  ),
  `</urlset>`,
].join("\n");

writeFileSync(resolve("public/sitemap.xml"), xml);
console.log(`sitemap.xml written (${entries.length} entries)`);
