// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List B2B garment products from Irha Apparels. Optionally filter by category slug (e.g. 'lederhosen', 'business-suits') or search text.",
  inputSchema: {
    category_slug: z.string().optional().describe("Filter by category slug, e.g. 'lederhosen'."),
    search: z.string().optional().describe("Case-insensitive substring match against product name."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_slug, search, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let query = supabase.from("products").select("id, slug, name, description, category_id, moq, materials, images").limit(limit);
    if (search) query = query.ilike("name", `%${search}%`);
    if (category_slug) {
      const { data: cat } = await supabase.from("categories").select("id").eq("slug", category_slug).maybeSingle();
      if (cat?.id) query = query.eq("category_id", cat.id);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${data?.length ?? 0} products.

${JSON.stringify(data, null, 2)}`
        }
      ],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List categories",
  description: "List all product categories with slug and description.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("categories").select("id, slug, name, description, parent_id").order("name").limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Found ${data?.length ?? 0} categories.

${JSON.stringify(data, null, 2)}` }
      ],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_faqs_default = defineTool3({
  name: "list_faqs",
  title: "List FAQs",
  description: "List published FAQ entries. Useful for buyer questions about MOQ, lead times, shipping, samples.",
  inputSchema: {
    search: z3.string().optional().describe("Substring match against question."),
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let query = supabase.from("faqs").select("id, question, answer, category, order_index").order("order_index", { ascending: true }).limit(limit);
    if (search) query = query.ilike("question", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { faqs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts (title, slug, excerpt, tags). Use get_blog_post for full body.",
  inputSchema: {
    search: z4.string().optional(),
    limit: z4.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    let query = supabase.from("blog_posts").select("id, slug, title, excerpt, tags, published_at").order("published_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z5 } from "npm:zod@^3.25.76";
var submit_inquiry_default = defineTool5({
  name: "submit_inquiry",
  title: "Submit B2B inquiry",
  description: "Submit a wholesale/B2B inquiry to Irha Apparels. Creates a lead the sales team will follow up on.",
  inputSchema: {
    name: z5.string().min(1).describe("Contact full name."),
    email: z5.string().email().describe("Contact email."),
    company: z5.string().optional(),
    country: z5.string().optional().describe("Buyer country (e.g. 'Germany')."),
    phone: z5.string().optional(),
    product_interest: z5.string().optional().describe("Which product / category the buyer is interested in."),
    quantity: z5.string().optional().describe("Estimated order quantity, e.g. '500 units'."),
    message: z5.string().min(1).describe("Free-form buyer message.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("inquiries").insert({
      name: input.name,
      email: input.email,
      company: input.company ?? null,
      country: input.country ?? null,
      phone: input.phone ?? null,
      product_interest: input.product_interest ?? null,
      quantity: input.quantity ?? null,
      message: input.message,
      source: "mcp"
    }).select("id").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Failed to submit: ${error.message}` }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Inquiry received. Reference #${data?.id}. The Irha Apparels team will reply within one business day.`
        }
      ],
      structuredContent: { inquiry_id: data?.id }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "irha-apparels-mcp",
  title: "Irha Apparels",
  version: "0.1.0",
  instructions: "Tools for Irha Apparels \u2014 a B2B garment manufacturer in Sialkot, Pakistan (lederhosen, dirndls, business suits, uniforms, sportswear). Use `list_categories` and `list_products` to explore the catalogue, `list_faqs` for buyer FAQs (MOQ, lead times, shipping), `list_blog_posts` for editorial content, and `submit_inquiry` to send a wholesale enquiry to the sales team.",
  tools: [list_products_default, list_categories_default, list_faqs_default, list_blog_posts_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
