-- IRHA GP-2 — Search measurement / commercial observability control plane.
-- Additive, RLS-first, no product/catalogue content mutation.

create table if not exists public.commercial_measurement_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default clock_timestamp(),
  event_name text not null check (event_name in (
    'page_view','organic_landing','campaign_landing','category_view','product_type_view','product_view',
    'manufacturing_resource_view','inquiry_cta_click','whatsapp_click','email_click','sample_cta_click',
    'quote_cta_click','rfq_start','rfq_submit','general_inquiry_submit','product_inquiry_submit'
  )),
  anonymous_session_hash text check (anonymous_session_hash is null or anonymous_session_hash ~ '^[0-9a-f]{64}$'),
  canonical_path text not null default '/',
  landing_path text,
  referrer_host text,
  source text,
  medium text,
  campaign text,
  content text,
  term text,
  product_id uuid references public.products(id) on delete set null,
  reference_code text,
  main_category text,
  audience_group text,
  product_type text,
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  device_type text check (device_type is null or device_type in ('mobile','tablet','desktop','unknown')),
  lead_kind text,
  lead_reference text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);

alter table public.commercial_measurement_events enable row level security;
revoke all on table public.commercial_measurement_events from public, anon, authenticated;
grant select, insert on table public.commercial_measurement_events to service_role;
grant usage, select on sequence public.commercial_measurement_events_id_seq to service_role;

create index if not exists commercial_measurement_events_name_time_idx
  on public.commercial_measurement_events (event_name, occurred_at desc);
create index if not exists commercial_measurement_events_path_time_idx
  on public.commercial_measurement_events (canonical_path, occurred_at desc);
create index if not exists commercial_measurement_events_product_time_idx
  on public.commercial_measurement_events (product_id, occurred_at desc) where product_id is not null;
create index if not exists commercial_measurement_events_source_time_idx
  on public.commercial_measurement_events (source, medium, occurred_at desc);

create table if not exists public.search_measurement_runs (
  id uuid primary key default gen_random_uuid(),
  property text not null default 'sc-domain:irhaapparels.com',
  started_at timestamptz not null default clock_timestamp(),
  completed_at timestamptz,
  status text not null check (status in ('running','complete','blocked','failed')) default 'running',
  failure_code text,
  permission_level text,
  data_start_date date,
  data_end_date date,
  current_rows integer not null default 0 check (current_rows >= 0),
  previous_rows integer not null default 0 check (previous_rows >= 0),
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.search_console_observations (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.search_measurement_runs(id) on delete cascade,
  period text not null check (period in ('current_28d','previous_28d')),
  dimension_type text not null check (dimension_type in ('query','page','country','device','query_page')),
  key_1 text not null,
  key_2 text not null default '',
  canonical_path text,
  clicks double precision not null default 0 check (clicks >= 0),
  impressions double precision not null default 0 check (impressions >= 0),
  ctr double precision not null default 0 check (ctr >= 0 and ctr <= 1),
  position double precision not null default 0 check (position >= 0),
  observed_at timestamptz not null default clock_timestamp(),
  unique (run_id, period, dimension_type, key_1, key_2)
);

alter table public.search_measurement_runs enable row level security;
alter table public.search_console_observations enable row level security;
revoke all on table public.search_measurement_runs from public, anon, authenticated;
revoke all on table public.search_console_observations from public, anon, authenticated;
grant select, insert, update on table public.search_measurement_runs to service_role;
grant select, insert on table public.search_console_observations to service_role;
grant usage, select on sequence public.search_console_observations_id_seq to service_role;

create index if not exists search_measurement_runs_completed_idx
  on public.search_measurement_runs (completed_at desc) where status = 'complete';
create index if not exists search_console_observations_run_dimension_idx
  on public.search_console_observations (run_id, period, dimension_type, impressions desc);
create index if not exists search_console_observations_path_idx
  on public.search_console_observations (run_id, period, canonical_path) where canonical_path is not null;

create or replace view public.gp2_product_search_observability as
with latest as (
  select id, completed_at
  from public.search_measurement_runs
  where status = 'complete'
  order by completed_at desc nulls last
  limit 1
), search_by_path as (
  select o.canonical_path,
         sum(o.clicks) as clicks,
         sum(o.impressions) as impressions,
         case when sum(o.impressions) > 0 then sum(o.clicks) / sum(o.impressions) else null end as ctr,
         case when sum(o.impressions) > 0 then sum(o.position * o.impressions) / sum(o.impressions) else null end as average_position
  from public.search_console_observations o
  join latest l on l.id = o.run_id
  where o.period = 'current_28d' and o.dimension_type = 'page'
  group by o.canonical_path
), intent_by_product as (
  select product_id,
         count(*) filter (where event_name = 'product_view') as product_views,
         count(*) filter (where event_name in ('inquiry_cta_click','whatsapp_click','email_click','sample_cta_click','quote_cta_click','rfq_start')) as intent_events,
         count(*) filter (where event_name in ('rfq_submit','general_inquiry_submit','product_inquiry_submit')) as submit_events,
         max(occurred_at) as last_intent_observed_at
  from public.commercial_measurement_events
  where occurred_at >= clock_timestamp() - interval '28 days'
  group by product_id
)
select p.id as product_id,
       p.reference_code,
       p.sku,
       p.name,
       p.main_category,
       p.audience_group,
       p.product_type,
       p.canonical_path,
       s.impressions,
       s.clicks,
       s.ctr,
       s.average_position,
       coalesce(i.product_views, 0) as product_views,
       coalesce(i.intent_events, 0) as intent_events,
       coalesce(i.submit_events, 0) as submit_events,
       i.last_intent_observed_at,
       l.completed_at as search_last_observed_at,
       case when s.canonical_path is null then 'NO DATA / NOT OBSERVED' else 'OBSERVED' end as search_data_state
from public.products p
left join search_by_path s on s.canonical_path = p.canonical_path
left join intent_by_product i on i.product_id = p.id
left join latest l on true
where p.is_published = true and p.publish_state = 'published';

create or replace view public.gp2_category_observability as
select p.main_category,
       count(*) as published_products,
       count(*) filter (where o.search_data_state = 'OBSERVED') as products_with_search_data,
       sum(coalesce(o.impressions, 0)) as observed_impressions,
       sum(coalesce(o.clicks, 0)) as observed_clicks,
       sum(coalesce(o.product_views, 0)) as product_views,
       sum(coalesce(o.intent_events, 0)) as intent_events,
       sum(coalesce(o.submit_events, 0)) as submit_events,
       max(o.search_last_observed_at) as search_last_observed_at
from public.products p
left join public.gp2_product_search_observability o on o.product_id = p.id
where p.is_published = true and p.publish_state = 'published'
group by p.main_category;

revoke all on public.gp2_product_search_observability from public, anon, authenticated;
revoke all on public.gp2_category_observability from public, anon, authenticated;
grant select on public.gp2_product_search_observability to service_role;
grant select on public.gp2_category_observability to service_role;

insert into private.edge_rate_limit_policies (
  policy_key, burst_limit, burst_window_seconds,
  sustained_limit, sustained_window_seconds,
  duplicate_limit, duplicate_window_seconds,
  global_limit, global_window_seconds, block_seconds
) values ('site-visitor.event', 40, 60, 1200, 86400, 1, 2, 30000, 600, 600)
on conflict (policy_key) do update set
  burst_limit = excluded.burst_limit,
  burst_window_seconds = excluded.burst_window_seconds,
  sustained_limit = excluded.sustained_limit,
  sustained_window_seconds = excluded.sustained_window_seconds,
  duplicate_limit = excluded.duplicate_limit,
  duplicate_window_seconds = excluded.duplicate_window_seconds,
  global_limit = excluded.global_limit,
  global_window_seconds = excluded.global_window_seconds,
  block_seconds = excluded.block_seconds,
  enabled = true,
  updated_at = clock_timestamp();

comment on table public.commercial_measurement_events is
  'GP-2 privacy-bounded event stream. Never store buyer names, email, phone, messages, filenames or arbitrary URL query strings.';
comment on table public.search_console_observations is
  'GP-2 sanitized Google Search Console observations. Absence of a row means NO DATA / NOT OBSERVED, not zero search performance.';
