-- Phase 5.2: verified Media Library reel and carousel render pipeline.
-- Safe to apply independently. No renderer secret is stored in database tables.

ALTER TABLE public.media_assets
  ADD COLUMN IF NOT EXISTS verification_status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS width_px integer,
  ADD COLUMN IF NOT EXISTS height_px integer,
  ADD COLUMN IF NOT EXISTS duration_ms integer,
  ADD COLUMN IF NOT EXISTS checksum_sha256 text,
  ADD COLUMN IF NOT EXISTS social_approved boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS social_approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS social_approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS media_assets_social_ready_idx
  ON public.media_assets (social_approved, verification_status, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.social_render_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL CHECK (char_length(btrim(title)) BETWEEN 3 AND 120),
  render_type text NOT NULL CHECK (render_type IN ('reel','carousel')),
  aspect_ratio text NOT NULL CHECK (aspect_ratio IN ('9:16','4:5','1:1')),
  requested_duration_seconds integer NOT NULL DEFAULT 0 CHECK (requested_duration_seconds BETWEEN 0 AND 60),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','owner_review','queued','rendering','ready','failed','cancelled')),
  manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
  renderer_provider text,
  renderer_job_id text,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  locked_at timestamptz,
  output_asset_id uuid REFERENCES public.media_assets(id) ON DELETE SET NULL,
  output_url text,
  output_verification jsonb,
  error_message text,
  owner_approved_at timestamptz,
  owner_approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.social_render_job_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES public.social_render_jobs(id) ON DELETE CASCADE,
  media_asset_id uuid NOT NULL REFERENCES public.media_assets(id) ON DELETE RESTRICT,
  position integer NOT NULL CHECK (position BETWEEN 1 AND 10),
  duration_ms integer CHECK (duration_ms IS NULL OR duration_ms BETWEEN 100 AND 10000),
  scene_text text,
  overlay_text text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, position),
  UNIQUE (job_id, media_asset_id)
);

CREATE TABLE IF NOT EXISTS public.social_render_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id uuid REFERENCES public.social_render_jobs(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  before_record jsonb,
  after_record jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS social_render_jobs_status_created_idx
  ON public.social_render_jobs (status, created_at DESC);
CREATE INDEX IF NOT EXISTS social_render_jobs_owner_review_idx
  ON public.social_render_jobs (owner_approved_at, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS social_render_items_job_position_idx
  ON public.social_render_job_items (job_id, position);
CREATE INDEX IF NOT EXISTS social_render_events_job_created_idx
  ON public.social_render_events (job_id, created_at DESC);

ALTER TABLE public.social_render_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_render_job_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_render_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='social_render_jobs' AND policyname='social_render_jobs_admin_all') THEN
    CREATE POLICY social_render_jobs_admin_all ON public.social_render_jobs
      FOR ALL TO authenticated
      USING (public.has_role(auth.uid(), 'admin'))
      WITH CHECK (public.has_role(auth.uid(), 'admin'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='social_render_job_items' AND policyname='social_render_job_items_admin_all') THEN
    CREATE POLICY social_render_job_items_admin_all ON public.social_render_job_items
      FOR ALL TO authenticated
      USING (public.has_role(auth.uid(), 'admin'))
      WITH CHECK (public.has_role(auth.uid(), 'admin'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='social_render_events' AND policyname='social_render_events_admin_select') THEN
    CREATE POLICY social_render_events_admin_select ON public.social_render_events
      FOR SELECT TO authenticated
      USING (public.has_role(auth.uid(), 'admin'));
  END IF;
END $$;

REVOKE ALL ON TABLE public.social_render_jobs FROM anon;
REVOKE ALL ON TABLE public.social_render_job_items FROM anon;
REVOKE ALL ON TABLE public.social_render_events FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.social_render_jobs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.social_render_job_items TO authenticated;
GRANT SELECT ON TABLE public.social_render_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.social_render_events_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.social_render_jobs_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  service_call boolean := COALESCE(auth.role() = 'service_role', false);
  files jsonb;
BEGIN
  IF NOT service_call AND (auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin')) THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;

  NEW.updated_at := now();
  IF NOT service_call THEN
    NEW.updated_by := auth.uid();
    IF TG_OP = 'INSERT' THEN NEW.created_by := COALESCE(NEW.created_by, auth.uid()); END IF;
  END IF;

  IF NEW.render_type = 'reel' THEN
    IF NEW.aspect_ratio <> '9:16' OR NEW.requested_duration_seconds <> 10 THEN
      RAISE EXCEPTION 'reel output must be 9:16 and 10 seconds';
    END IF;
  ELSE
    NEW.requested_duration_seconds := 0;
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status THEN
    IF NOT (
      (OLD.status = 'draft' AND NEW.status IN ('owner_review','cancelled')) OR
      (OLD.status = 'owner_review' AND NEW.status IN ('draft','queued','cancelled')) OR
      (OLD.status = 'queued' AND NEW.status IN ('rendering','failed','cancelled')) OR
      (OLD.status = 'rendering' AND NEW.status IN ('ready','failed','cancelled')) OR
      (OLD.status = 'failed' AND NEW.status IN ('draft','queued','cancelled'))
    ) THEN
      RAISE EXCEPTION 'invalid social render transition: % -> %', OLD.status, NEW.status;
    END IF;
  END IF;

  IF NEW.status IN ('queued','rendering','ready') AND (NEW.owner_approved_at IS NULL OR NEW.owner_approved_by IS NULL) THEN
    RAISE EXCEPTION 'owner approval is required before renderer queue';
  END IF;

  IF NEW.status = 'ready' THEN
    IF COALESCE(NEW.output_verification->>'verified','false') <> 'true' THEN
      RAISE EXCEPTION 'verified output evidence is required';
    END IF;

    IF NEW.render_type = 'reel' THEN
      IF NEW.output_asset_id IS NULL OR NEW.output_url !~ '^https://' THEN
        RAISE EXCEPTION 'reel output asset and HTTPS URL are required';
      END IF;
      IF COALESCE(NEW.output_verification->>'checksumSha256','') !~ '^[A-Fa-f0-9]{64}$' THEN
        RAISE EXCEPTION 'reel SHA-256 checksum is required';
      END IF;
      IF COALESCE(NEW.output_verification->>'mimeType','') !~ '^video/' THEN
        RAISE EXCEPTION 'reel output must be a video';
      END IF;
      IF COALESCE((NEW.output_verification->>'durationSeconds')::numeric, 0) NOT BETWEEN 9.5 AND 10.5 THEN
        RAISE EXCEPTION 'verified reel duration must be approximately 10 seconds';
      END IF;
    ELSE
      files := NEW.output_verification->'files';
      IF jsonb_typeof(files) <> 'array' OR jsonb_array_length(files) NOT BETWEEN 2 AND 10 THEN
        RAISE EXCEPTION 'carousel requires 2 to 10 verified output files';
      END IF;
      IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(files) AS file
        WHERE COALESCE(file->>'mediaAssetId','') = ''
           OR COALESCE(file->>'url','') !~ '^https://'
           OR COALESCE(file->>'checksumSha256','') !~ '^[A-Fa-f0-9]{64}$'
           OR COALESCE(file->>'mimeType','') !~ '^image/'
           OR COALESCE(file->>'width','') = ''
           OR COALESCE(file->>'height','') = ''
           OR COALESCE(file->>'sizeBytes','') = ''
           OR COALESCE(file->>'position','') = ''
      ) THEN
        RAISE EXCEPTION 'each carousel output requires asset, URL, checksum, image type, dimensions, size and position';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_render_items_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  job_status text;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  SELECT status INTO job_status FROM public.social_render_jobs WHERE id = NEW.job_id;
  IF job_status <> 'draft' THEN
    RAISE EXCEPTION 'render items can only change while job is draft';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_render_job_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.social_render_events (job_id, event_type, actor_id, before_record, after_record)
  VALUES (
    COALESCE(NEW.id, OLD.id),
    lower(TG_OP),
    auth.uid(),
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS social_render_jobs_before_write_trigger ON public.social_render_jobs;
CREATE TRIGGER social_render_jobs_before_write_trigger
  BEFORE INSERT OR UPDATE ON public.social_render_jobs
  FOR EACH ROW EXECUTE FUNCTION public.social_render_jobs_before_write();

DROP TRIGGER IF EXISTS social_render_items_before_write_trigger ON public.social_render_job_items;
CREATE TRIGGER social_render_items_before_write_trigger
  BEFORE INSERT OR UPDATE ON public.social_render_job_items
  FOR EACH ROW EXECUTE FUNCTION public.social_render_items_before_write();

DROP TRIGGER IF EXISTS social_render_job_audit_trigger ON public.social_render_jobs;
CREATE TRIGGER social_render_job_audit_trigger
  AFTER INSERT OR UPDATE OR DELETE ON public.social_render_jobs
  FOR EACH ROW EXECUTE FUNCTION public.social_render_job_audit();

REVOKE ALL ON FUNCTION public.social_render_jobs_before_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.social_render_items_before_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.social_render_job_audit() FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.admin_submit_social_render_job(_job_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  job public.social_render_jobs%ROWTYPE;
  item_count integer;
  total_duration integer;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO job FROM public.social_render_jobs WHERE id = _job_id FOR UPDATE;
  IF NOT FOUND OR job.status <> 'draft' THEN RAISE EXCEPTION 'draft render job required'; END IF;

  SELECT count(*), COALESCE(sum(duration_ms), 0)
  INTO item_count, total_duration
  FROM public.social_render_job_items WHERE job_id = _job_id;

  IF job.render_type = 'reel' AND (item_count <> 5 OR total_duration <> 10000) THEN
    RAISE EXCEPTION 'reel requires exactly five scenes totaling 10000 ms';
  END IF;
  IF job.render_type = 'carousel' AND item_count NOT BETWEEN 2 AND 10 THEN
    RAISE EXCEPTION 'carousel requires 2 to 10 slides';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM public.social_render_job_items item
    JOIN public.media_assets asset ON asset.id = item.media_asset_id
    WHERE item.job_id = _job_id
      AND (asset.status <> 'active' OR asset.public_url !~ '^https://' OR asset.mime_type !~ '^(image|video)/')
  ) THEN
    RAISE EXCEPTION 'all render inputs must be active HTTPS image or video assets';
  END IF;

  UPDATE public.social_render_jobs SET status = 'owner_review', error_message = NULL WHERE id = _job_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_approve_social_render_job(_job_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.social_render_jobs
  SET status = 'queued', owner_approved_at = now(), owner_approved_by = auth.uid(), error_message = NULL
  WHERE id = _job_id AND status = 'owner_review';
  IF NOT FOUND THEN RAISE EXCEPTION 'owner-review render job required'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_retry_social_render_job(_job_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.social_render_jobs
  SET status = 'queued', error_message = NULL, renderer_job_id = NULL, locked_at = NULL
  WHERE id = _job_id AND status = 'failed' AND owner_approved_at IS NOT NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'approved failed render job required'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_cancel_social_render_job(_job_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.social_render_jobs SET status = 'cancelled'
  WHERE id = _job_id AND status IN ('draft','owner_review','queued');
  IF NOT FOUND THEN RAISE EXCEPTION 'job can no longer be cancelled from admin'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_next_social_render_job(_provider text)
RETURNS public.social_render_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  claimed public.social_render_jobs%ROWTYPE;
BEGIN
  IF COALESCE(auth.role(),'') <> 'service_role' THEN
    RAISE EXCEPTION 'service role required' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO claimed
  FROM public.social_render_jobs
  WHERE status = 'queued'
  ORDER BY created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1;
  IF NOT FOUND THEN RETURN NULL; END IF;
  UPDATE public.social_render_jobs
  SET status = 'rendering', renderer_provider = left(btrim(_provider), 80), locked_at = now(), attempt_count = attempt_count + 1
  WHERE id = claimed.id
  RETURNING * INTO claimed;
  RETURN claimed;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_social_render_job(
  _job_id uuid,
  _renderer_job_id text,
  _output_asset_id uuid,
  _output_url text,
  _verification jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF COALESCE(auth.role(),'') <> 'service_role' THEN
    RAISE EXCEPTION 'service role required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.social_render_jobs
  SET status = 'ready', renderer_job_id = nullif(btrim(_renderer_job_id),''), output_asset_id = _output_asset_id,
      output_url = nullif(btrim(_output_url),''), output_verification = _verification, error_message = NULL
  WHERE id = _job_id AND status = 'rendering';
  IF NOT FOUND THEN RAISE EXCEPTION 'rendering job required'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_social_render_job(_job_id uuid, _message text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF COALESCE(auth.role(),'') <> 'service_role' THEN
    RAISE EXCEPTION 'service role required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.social_render_jobs
  SET status = 'failed', error_message = left(coalesce(nullif(btrim(_message),''),'Renderer failed without detail'), 2000)
  WHERE id = _job_id AND status IN ('queued','rendering');
  IF NOT FOUND THEN RAISE EXCEPTION 'queued or rendering job required'; END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_submit_social_render_job(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_approve_social_render_job(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_retry_social_render_job(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_cancel_social_render_job(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_submit_social_render_job(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_approve_social_render_job(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_retry_social_render_job(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_social_render_job(uuid) TO authenticated;

REVOKE ALL ON FUNCTION public.claim_next_social_render_job(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_social_render_job(uuid,text,uuid,text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.fail_social_render_job(uuid,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_next_social_render_job(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_social_render_job(uuid,text,uuid,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_social_render_job(uuid,text) TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'social-renders',
  'social-renders',
  true,
  104857600,
  ARRAY['image/jpeg','image/png','image/webp','video/mp4','video/webm']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='social_renders_admin_select') THEN
    CREATE POLICY social_renders_admin_select ON storage.objects FOR SELECT TO authenticated
      USING (bucket_id='social-renders' AND public.has_role(auth.uid(), 'admin'));
  END IF;
END $$;
