-- Phase 2 / Batch 2.4: global website settings and reusable Media Library.
-- Deferred per owner instruction; apply once during final backend activation.

CREATE TABLE IF NOT EXISTS public.media_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bucket text NOT NULL DEFAULT 'site-media',
  object_path text NOT NULL UNIQUE,
  public_url text NOT NULL,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 26214400),
  title text,
  alt_text text,
  tags text[] NOT NULL DEFAULT '{}',
  usage_notes text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS media_assets_status_created_idx
  ON public.media_assets (status, created_at DESC);
CREATE INDEX IF NOT EXISTS media_assets_tags_gin_idx
  ON public.media_assets USING gin (tags);

CREATE TABLE IF NOT EXISTS public.media_asset_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_asset_id uuid REFERENCES public.media_assets(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  before_record jsonb,
  after_record jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_asset_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='media_assets' AND policyname='media_assets_admin_all') THEN
    CREATE POLICY media_assets_admin_all ON public.media_assets
      FOR ALL TO authenticated
      USING (public.has_role(auth.uid(), 'admin'))
      WITH CHECK (public.has_role(auth.uid(), 'admin'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='media_asset_events' AND policyname='media_asset_events_admin_select') THEN
    CREATE POLICY media_asset_events_admin_select ON public.media_asset_events
      FOR SELECT TO authenticated
      USING (public.has_role(auth.uid(), 'admin'));
  END IF;
END $$;

REVOKE ALL ON TABLE public.media_assets FROM anon;
REVOKE ALL ON TABLE public.media_asset_events FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.media_assets TO authenticated;
GRANT SELECT ON TABLE public.media_asset_events TO authenticated;

CREATE OR REPLACE FUNCTION public.media_assets_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  IF TG_OP = 'INSERT' THEN NEW.created_by := COALESCE(NEW.created_by, auth.uid()); END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.media_assets_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.media_asset_events (media_asset_id, action, actor_id, before_record, after_record)
  VALUES (
    COALESCE(NEW.id, OLD.id),
    lower(TG_OP),
    auth.uid(),
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS media_assets_before_write_trigger ON public.media_assets;
CREATE TRIGGER media_assets_before_write_trigger
  BEFORE INSERT OR UPDATE ON public.media_assets
  FOR EACH ROW EXECUTE FUNCTION public.media_assets_before_write();

DROP TRIGGER IF EXISTS media_assets_audit_trigger ON public.media_assets;
CREATE TRIGGER media_assets_audit_trigger
  AFTER INSERT OR UPDATE OR DELETE ON public.media_assets
  FOR EACH ROW EXECUTE FUNCTION public.media_assets_audit();

REVOKE ALL ON FUNCTION public.media_assets_before_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.media_assets_audit() FROM PUBLIC;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'site-media',
  'site-media',
  true,
  26214400,
  ARRAY['image/jpeg','image/png','image/webp','image/gif','image/svg+xml','application/pdf','video/mp4','video/webm']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='site_media_admin_insert') THEN
    CREATE POLICY site_media_admin_insert ON storage.objects FOR INSERT TO authenticated
      WITH CHECK (bucket_id='site-media' AND public.has_role(auth.uid(), 'admin'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='site_media_admin_update') THEN
    CREATE POLICY site_media_admin_update ON storage.objects FOR UPDATE TO authenticated
      USING (bucket_id='site-media' AND public.has_role(auth.uid(), 'admin'))
      WITH CHECK (bucket_id='site-media' AND public.has_role(auth.uid(), 'admin'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='site_media_admin_delete') THEN
    CREATE POLICY site_media_admin_delete ON storage.objects FOR DELETE TO authenticated
      USING (bucket_id='site-media' AND public.has_role(auth.uid(), 'admin'));
  END IF;
END $$;

-- Seed verified current public settings without changing the existing live presentation.
INSERT INTO public.cms_documents (
  document_key, document_type, title, draft_content, published_content,
  status, version, published_version, created_at, updated_at, published_at
)
VALUES (
  'site.global.settings',
  'site_settings',
  'Global Website Settings',
  $json$
  {
    "brand":{"name":"Irha Apparels","tagline":"B2B Custom Apparel Manufacturer","location":"Sialkot, Pakistan","address":"Sialkot, Punjab, Pakistan","email":"irhaapparelsofficial@gmail.com","phone":"+923204110066","phoneDisplay":"+92 320 411 0066","whatsappNumber":"923204110066","logoUrl":""},
    "navigation":{"main":[{"label":"Home","href":"/","enabled":true},{"label":"About","href":"/about","enabled":true},{"label":"Collections","href":"/products","enabled":true},{"label":"Manufacturing","href":"/manufacturing","enabled":true}],"more":[{"label":"Buyer Trust","href":"/buyer-trust","enabled":true},{"label":"Factory Video Call","href":"/factory-video-call","enabled":true},{"label":"Buyer Resources","href":"/resources","enabled":true},{"label":"Buyer FAQ","href":"/faq","enabled":true},{"label":"Blog","href":"/blog","enabled":true},{"label":"Catalogue","href":"/catalogue","enabled":true},{"label":"Compliance","href":"/compliance","enabled":true},{"label":"Shortlist","href":"/shortlist","enabled":true}],"tail":[{"label":"Inquiry","href":"/inquiry","enabled":true},{"label":"Contact","href":"/contact","enabled":true}]},
    "ctas":{"quoteLabel":"Get Quote","quoteHref":"/inquiry?intent=rfq","mockupLabel":"Mockup Design","studioLabel":"AI Designer","studioHref":"/studio","whatsappLabel":"WhatsApp"},
    "socials":{"instagram":"https://www.instagram.com/irhaapparels","facebook":"https://web.facebook.com/profile.php?id=61590950402472","tiktok":"https://www.tiktok.com/@irhaapparels"},
    "footer":{"intro":"B2B Custom Apparel Manufacturer","collectionLinks":[{"label":"Bavarian & Trachten","href":"/products/bavarian-trachten-wear","enabled":true},{"label":"Premium Leather","href":"/products/premium-leather-apparel","enabled":true},{"label":"Sportswear","href":"/products/sportswear","enabled":true},{"label":"Streetwear & Activewear","href":"/products/streetwear-activewear","enabled":true},{"label":"Leisure & Nightwear","href":"/products/leisure-nightwear","enabled":true}],"companyLinks":[{"label":"Catalogue","href":"/catalogue","enabled":true},{"label":"About","href":"/about","enabled":true},{"label":"Manufacturing","href":"/manufacturing","enabled":true},{"label":"Buyer Trust Center","href":"/buyer-trust","enabled":true},{"label":"Factory Video Call","href":"/factory-video-call","enabled":true},{"label":"Buyer Resources","href":"/resources","enabled":true},{"label":"Buyer FAQ","href":"/faq","enabled":true},{"label":"Blog","href":"/blog","enabled":true},{"label":"Compliance","href":"/compliance","enabled":true},{"label":"Contact","href":"/contact","enabled":true}],"buyerReadiness":[{"label":"Requirement-led review","note":"Scope confirmed before commitment"},{"label":"Private-label options","note":"Labels, tags and packaging by program"},{"label":"Order documentation","note":"Requirements confirmed before dispatch"},{"label":"Live factory view","note":"Available by scheduled video call"}],"factoryCallLabel":"Request live factory call","factoryCallHref":"/factory-video-call","stripText":"MOQ · Timing · Pricing confirmed per program | OEM · ODM · Private Label","copyrightSuffix":"All rights reserved."},
    "announcement":{"mode":"calendar","id":"custom-announcement","label":"Production Update","message":"Share your program requirements for a tailored production review.","ctaLabel":"Discuss a Program","ctaHref":"/inquiry?intent=rfq","startDate":"","endDate":"","theme":"gold","dismissible":true}
  }
  $json$::jsonb,
  $json$
  {
    "brand":{"name":"Irha Apparels","tagline":"B2B Custom Apparel Manufacturer","location":"Sialkot, Pakistan","address":"Sialkot, Punjab, Pakistan","email":"irhaapparelsofficial@gmail.com","phone":"+923204110066","phoneDisplay":"+92 320 411 0066","whatsappNumber":"923204110066","logoUrl":""},
    "navigation":{"main":[{"label":"Home","href":"/","enabled":true},{"label":"About","href":"/about","enabled":true},{"label":"Collections","href":"/products","enabled":true},{"label":"Manufacturing","href":"/manufacturing","enabled":true}],"more":[{"label":"Buyer Trust","href":"/buyer-trust","enabled":true},{"label":"Factory Video Call","href":"/factory-video-call","enabled":true},{"label":"Buyer Resources","href":"/resources","enabled":true},{"label":"Buyer FAQ","href":"/faq","enabled":true},{"label":"Blog","href":"/blog","enabled":true},{"label":"Catalogue","href":"/catalogue","enabled":true},{"label":"Compliance","href":"/compliance","enabled":true},{"label":"Shortlist","href":"/shortlist","enabled":true}],"tail":[{"label":"Inquiry","href":"/inquiry","enabled":true},{"label":"Contact","href":"/contact","enabled":true}]},
    "ctas":{"quoteLabel":"Get Quote","quoteHref":"/inquiry?intent=rfq","mockupLabel":"Mockup Design","studioLabel":"AI Designer","studioHref":"/studio","whatsappLabel":"WhatsApp"},
    "socials":{"instagram":"https://www.instagram.com/irhaapparels","facebook":"https://web.facebook.com/profile.php?id=61590950402472","tiktok":"https://www.tiktok.com/@irhaapparels"},
    "footer":{"intro":"B2B Custom Apparel Manufacturer","collectionLinks":[{"label":"Bavarian & Trachten","href":"/products/bavarian-trachten-wear","enabled":true},{"label":"Premium Leather","href":"/products/premium-leather-apparel","enabled":true},{"label":"Sportswear","href":"/products/sportswear","enabled":true},{"label":"Streetwear & Activewear","href":"/products/streetwear-activewear","enabled":true},{"label":"Leisure & Nightwear","href":"/products/leisure-nightwear","enabled":true}],"companyLinks":[{"label":"Catalogue","href":"/catalogue","enabled":true},{"label":"About","href":"/about","enabled":true},{"label":"Manufacturing","href":"/manufacturing","enabled":true},{"label":"Buyer Trust Center","href":"/buyer-trust","enabled":true},{"label":"Factory Video Call","href":"/factory-video-call","enabled":true},{"label":"Buyer Resources","href":"/resources","enabled":true},{"label":"Buyer FAQ","href":"/faq","enabled":true},{"label":"Blog","href":"/blog","enabled":true},{"label":"Compliance","href":"/compliance","enabled":true},{"label":"Contact","href":"/contact","enabled":true}],"buyerReadiness":[{"label":"Requirement-led review","note":"Scope confirmed before commitment"},{"label":"Private-label options","note":"Labels, tags and packaging by program"},{"label":"Order documentation","note":"Requirements confirmed before dispatch"},{"label":"Live factory view","note":"Available by scheduled video call"}],"factoryCallLabel":"Request live factory call","factoryCallHref":"/factory-video-call","stripText":"MOQ · Timing · Pricing confirmed per program | OEM · ODM · Private Label","copyrightSuffix":"All rights reserved."},
    "announcement":{"mode":"calendar","id":"custom-announcement","label":"Production Update","message":"Share your program requirements for a tailored production review.","ctaLabel":"Discuss a Program","ctaHref":"/inquiry?intent=rfq","startDate":"","endDate":"","theme":"gold","dismissible":true}
  }
  $json$::jsonb,
  'published', 1, 1, now(), now(), now()
)
ON CONFLICT (document_key) DO NOTHING;

INSERT INTO public.cms_document_revisions (document_id, version, content, action)
SELECT id, 1, published_content, 'published'
FROM public.cms_documents d
WHERE d.document_key='site.global.settings'
  AND NOT EXISTS (SELECT 1 FROM public.cms_document_revisions r WHERE r.document_id=d.id);
