-- Phase 5.3: owner-approved social publishing scheduler.
-- Source only. Apply during the final one-time backend activation.

CREATE TABLE IF NOT EXISTS public.social_platform_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform text NOT NULL UNIQUE CHECK (platform IN ('facebook','instagram','linkedin','tiktok')),
  display_name text NOT NULL,
  external_account_id text,
  enabled boolean NOT NULL DEFAULT false,
  verification_status text NOT NULL DEFAULT 'missing' CHECK (verification_status IN ('missing','pending','verified','failed')),
  capabilities jsonb NOT NULL DEFAULT '{"text":false,"image":false,"carousel":false,"reel":false}'::jsonb,
  last_verified_at timestamptz,
  last_health jsonb NOT NULL DEFAULT '{}'::jsonb,
  connection_note text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.social_platform_accounts (platform, display_name, capabilities)
VALUES
  ('facebook', 'Facebook Page', '{"text":true,"image":true,"carousel":false,"reel":true}'::jsonb),
  ('instagram', 'Instagram Business', '{"text":false,"image":true,"carousel":false,"reel":true}'::jsonb),
  ('linkedin', 'LinkedIn', '{"text":true,"image":false,"carousel":false,"reel":false}'::jsonb),
  ('tiktok', 'TikTok Business', '{"text":false,"image":false,"carousel":false,"reel":false}'::jsonb)
ON CONFLICT (platform) DO NOTHING;

ALTER TABLE public.social_calendar_items
  ADD COLUMN IF NOT EXISTS platform_account_id uuid REFERENCES public.social_platform_accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_render_job_id uuid REFERENCES public.social_render_jobs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_media_asset_id uuid REFERENCES public.media_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS render_verified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS delivery_mode text NOT NULL DEFAULT 'manual' CHECK (delivery_mode IN ('manual','automatic')),
  ADD COLUMN IF NOT EXISTS publish_approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS publish_approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz,
  ADD COLUMN IF NOT EXISTS max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS delivery_lock_token uuid,
  ADD COLUMN IF NOT EXISTS delivery_locked_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_attempt_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_worker_id text;

CREATE TABLE IF NOT EXISTS public.social_publish_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  worker_id text NOT NULL,
  trigger_source text NOT NULL CHECK (trigger_source IN ('admin','scheduler','retry')),
  status text NOT NULL DEFAULT 'running' CHECK (status IN ('running','completed','partial','failed')),
  claimed_count integer NOT NULL DEFAULT 0,
  published_count integer NOT NULL DEFAULT 0,
  manual_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.social_publish_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id uuid REFERENCES public.social_calendar_items(id) ON DELETE SET NULL,
  run_id uuid REFERENCES public.social_publish_runs(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (event_type IN ('render_attached','publication_approved','publication_revoked','claimed','published','verified_only','manual_required','failed')),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  worker_id text,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS social_accounts_status_idx ON public.social_platform_accounts (enabled, verification_status, platform);
CREATE INDEX IF NOT EXISTS social_calendar_auto_due_idx ON public.social_calendar_items (next_attempt_at, scheduled_at, created_at)
  WHERE delivery_mode='automatic' AND publish_approved_at IS NOT NULL AND status IN ('scheduled','ready','failed');
CREATE INDEX IF NOT EXISTS social_calendar_render_job_idx ON public.social_calendar_items (source_render_job_id) WHERE source_render_job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS social_publish_runs_started_idx ON public.social_publish_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS social_publish_events_item_idx ON public.social_publish_events (item_id, created_at DESC);

ALTER TABLE public.social_platform_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_publish_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_publish_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY social_platform_accounts_admin_all ON public.social_platform_accounts
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'))
    WITH CHECK (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY social_publish_runs_admin_select ON public.social_publish_runs
    FOR SELECT TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY social_publish_events_admin_select ON public.social_publish_events
    FOR SELECT TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

REVOKE ALL ON public.social_platform_accounts, public.social_publish_runs, public.social_publish_events FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.social_platform_accounts TO authenticated;
GRANT SELECT ON public.social_publish_runs, public.social_publish_events TO authenticated;
GRANT ALL ON public.social_platform_accounts, public.social_publish_runs, public.social_publish_events TO service_role;

-- Delivery attempts are immutable evidence for browser admins.
REVOKE INSERT, UPDATE, DELETE ON public.social_delivery_attempts FROM authenticated;
GRANT SELECT ON public.social_delivery_attempts TO authenticated;

CREATE OR REPLACE FUNCTION public.social_platform_account_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  IF jsonb_typeof(NEW.capabilities) <> 'object' THEN
    RAISE EXCEPTION 'capabilities must be an object';
  END IF;
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  IF TG_OP='INSERT' THEN NEW.created_by := COALESCE(NEW.created_by, auth.uid()); END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS social_platform_account_before_write_trigger ON public.social_platform_accounts;
CREATE TRIGGER social_platform_account_before_write_trigger
  BEFORE INSERT OR UPDATE ON public.social_platform_accounts
  FOR EACH ROW EXECUTE FUNCTION public.social_platform_account_before_write();

REVOKE ALL ON FUNCTION public.social_platform_account_before_write() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.social_attach_verified_render(_item_id uuid, _render_job_id uuid)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _item public.social_calendar_items;
  _job public.social_render_jobs;
  _asset public.media_assets;
  _result public.social_calendar_items;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  SELECT * INTO _item FROM public.social_calendar_items WHERE id=_item_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'calendar item not found'; END IF;
  IF _item.status IN ('publishing','published') THEN RAISE EXCEPTION 'item cannot be changed from status %', _item.status; END IF;
  SELECT * INTO _job FROM public.social_render_jobs WHERE id=_render_job_id;
  IF NOT FOUND OR _job.status <> 'ready' OR _job.output_asset_id IS NULL THEN
    RAISE EXCEPTION 'render job is not verified ready';
  END IF;
  SELECT * INTO _asset FROM public.media_assets WHERE id=_job.output_asset_id;
  IF NOT FOUND OR _asset.status <> 'active' OR _asset.verification_status <> 'verified' OR COALESCE(_asset.social_approved,false) IS NOT TRUE THEN
    RAISE EXCEPTION 'output media is not verified and social-approved';
  END IF;
  IF _item.content_type='reel' AND _asset.mime_type NOT LIKE 'video/%' THEN
    RAISE EXCEPTION 'reel requires a verified video output';
  END IF;
  IF _item.content_type='carousel' AND _job.render_type <> 'carousel' THEN
    RAISE EXCEPTION 'carousel item requires a carousel render job';
  END IF;

  UPDATE public.social_calendar_items
  SET source_render_job_id=_job.id,
      source_media_asset_id=_asset.id,
      render_verified=true,
      image_url=CASE WHEN _asset.mime_type LIKE 'image/%' THEN _asset.public_url ELSE image_url END,
      video_url=CASE WHEN _asset.mime_type LIKE 'video/%' THEN _asset.public_url ELSE video_url END,
      creative_status='ready',
      publish_approved_by=NULL,
      publish_approved_at=NULL,
      delivery_mode='manual',
      next_attempt_at=NULL,
      error=NULL
  WHERE id=_item_id
  RETURNING * INTO _result;

  INSERT INTO public.social_publish_events(item_id,event_type,actor_id,detail)
  VALUES (_item_id,'render_attached',auth.uid(),jsonb_build_object('render_job_id',_job.id,'media_asset_id',_asset.id));
  RETURN _result;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_request_publication(
  _item_id uuid,
  _scheduled_at timestamptz DEFAULT NULL,
  _timezone text DEFAULT 'Asia/Karachi',
  _delivery_mode text DEFAULT 'automatic'
)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _item public.social_calendar_items;
  _account public.social_platform_accounts;
  _capability text;
  _result public.social_calendar_items;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  IF _delivery_mode NOT IN ('manual','automatic') THEN RAISE EXCEPTION 'invalid delivery mode'; END IF;
  IF char_length(btrim(COALESCE(_timezone,''))) < 3 OR char_length(_timezone) > 80 THEN RAISE EXCEPTION 'valid timezone required'; END IF;
  SELECT * INTO _item FROM public.social_calendar_items WHERE id=_item_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'calendar item not found'; END IF;
  IF _item.status IN ('publishing','published','verified_only','manual_required','cancelled') THEN
    RAISE EXCEPTION 'item cannot be approved from status %', _item.status;
  END IF;
  IF _item.approved_at IS NULL OR _item.approved_by IS NULL THEN
    RAISE EXCEPTION 'content approval is required before public publication approval';
  END IF;
  SELECT * INTO _account FROM public.social_platform_accounts WHERE platform=_item.platform;
  IF NOT FOUND OR NOT _account.enabled OR _account.verification_status <> 'verified' THEN
    RAISE EXCEPTION 'verified enabled platform account required';
  END IF;
  _capability := CASE _item.content_type WHEN 'text' THEN 'text' WHEN 'single_image' THEN 'image' WHEN 'carousel' THEN 'carousel' ELSE 'reel' END;
  IF COALESCE((_account.capabilities->>_capability)::boolean,false) IS NOT TRUE THEN
    RAISE EXCEPTION 'platform account does not verify % capability', _capability;
  END IF;
  IF _item.content_type='single_image' AND COALESCE(_item.image_url,'') !~ '^https://' THEN
    RAISE EXCEPTION 'public HTTPS image required';
  END IF;
  IF _item.content_type='reel' AND (COALESCE(_item.video_url,'') !~ '^https://' OR NOT _item.render_verified) THEN
    RAISE EXCEPTION 'verified public reel output required';
  END IF;
  IF _item.content_type='carousel' AND NOT _item.render_verified THEN
    RAISE EXCEPTION 'verified carousel output required';
  END IF;

  UPDATE public.social_calendar_items
  SET platform_account_id=_account.id,
      publish_approved_by=auth.uid(),
      publish_approved_at=now(),
      scheduled_at=COALESCE(_scheduled_at, now()),
      timezone=_timezone,
      delivery_mode=_delivery_mode,
      next_attempt_at=COALESCE(_scheduled_at, now()),
      delivery_lock_token=NULL,
      delivery_locked_at=NULL,
      status=CASE WHEN COALESCE(_scheduled_at,now()) > now() THEN 'scheduled' ELSE 'ready' END,
      error=NULL
  WHERE id=_item_id
  RETURNING * INTO _result;

  INSERT INTO public.social_publish_events(item_id,event_type,actor_id,detail)
  VALUES (_item_id,'publication_approved',auth.uid(),jsonb_build_object('scheduled_at',_result.scheduled_at,'timezone',_timezone,'delivery_mode',_delivery_mode));
  RETURN _result;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_revoke_publication(_item_id uuid)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE _result public.social_calendar_items;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  UPDATE public.social_calendar_items
  SET publish_approved_by=NULL,publish_approved_at=NULL,delivery_mode='manual',next_attempt_at=NULL,
      delivery_lock_token=NULL,delivery_locked_at=NULL,status='draft'
  WHERE id=_item_id AND status NOT IN ('publishing','published')
  RETURNING * INTO _result;
  IF NOT FOUND THEN RAISE EXCEPTION 'publication approval cannot be revoked'; END IF;
  INSERT INTO public.social_publish_events(item_id,event_type,actor_id) VALUES (_item_id,'publication_revoked',auth.uid());
  RETURN _result;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_claim_due_publications(_worker_id text, _limit integer DEFAULT 10)
RETURNS SETOF public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF;
  IF char_length(btrim(COALESCE(_worker_id,''))) < 3 THEN RAISE EXCEPTION 'worker id required'; END IF;
  RETURN QUERY
  WITH candidates AS (
    SELECT id
    FROM public.social_calendar_items
    WHERE delivery_mode='automatic'
      AND publish_approved_at IS NOT NULL
      AND status IN ('scheduled','ready','failed')
      AND publish_attempts < max_attempts
      AND COALESCE(scheduled_at,now()) <= now()
      AND COALESCE(next_attempt_at,scheduled_at,now()) <= now()
      AND (delivery_locked_at IS NULL OR delivery_locked_at < now() - interval '15 minutes')
    ORDER BY COALESCE(next_attempt_at,scheduled_at,created_at), created_at
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(COALESCE(_limit,10),1),25)
  ), updated AS (
    UPDATE public.social_calendar_items i
    SET status='publishing',delivery_lock_token=gen_random_uuid(),delivery_locked_at=now(),last_worker_id=_worker_id,error=NULL
    FROM candidates c WHERE i.id=c.id
    RETURNING i.*
  )
  SELECT * FROM updated;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_complete_publication(
  _item_id uuid,
  _lock_token uuid,
  _run_id uuid,
  _status text,
  _external_post_id text DEFAULT NULL,
  _external_post_url text DEFAULT NULL,
  _connector_result jsonb DEFAULT '{}'::jsonb,
  _error text DEFAULT NULL
)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE _result public.social_calendar_items;
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF;
  IF _status NOT IN ('published','verified_only','manual_required') THEN RAISE EXCEPTION 'invalid completion status'; END IF;
  IF _status='published' AND COALESCE(btrim(_external_post_id),'')='' AND COALESCE(_external_post_url,'') !~ '^https://' THEN
    RAISE EXCEPTION 'published status requires a real post id or HTTPS URL';
  END IF;
  UPDATE public.social_calendar_items
  SET status=_status,
      publish_attempts=publish_attempts+1,
      last_attempt_at=now(),
      next_attempt_at=NULL,
      delivery_lock_token=NULL,
      delivery_locked_at=NULL,
      external_post_id=NULLIF(btrim(_external_post_id),''),
      external_post_url=CASE WHEN COALESCE(_external_post_url,'') ~ '^https://' THEN _external_post_url ELSE NULL END,
      connector_result=COALESCE(_connector_result,'{}'::jsonb),
      error=NULLIF(left(COALESCE(_error,''),2000),''),
      published_at=CASE WHEN _status='published' THEN now() ELSE NULL END
  WHERE id=_item_id AND delivery_lock_token=_lock_token AND status='publishing'
  RETURNING * INTO _result;
  IF NOT FOUND THEN RAISE EXCEPTION 'delivery lock mismatch'; END IF;
  INSERT INTO public.social_publish_events(item_id,run_id,event_type,worker_id,detail)
  VALUES (_item_id,_run_id,_status,_result.last_worker_id,jsonb_build_object('post_id',_result.external_post_id,'post_url',_result.external_post_url));
  RETURN _result;
END;
$$;

CREATE OR REPLACE FUNCTION public.social_fail_publication(
  _item_id uuid,
  _lock_token uuid,
  _run_id uuid,
  _error text,
  _connector_result jsonb DEFAULT '{}'::jsonb
)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE _result public.social_calendar_items; _next_attempt integer;
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'service role required' USING ERRCODE='42501'; END IF;
  SELECT publish_attempts+1 INTO _next_attempt FROM public.social_calendar_items WHERE id=_item_id AND delivery_lock_token=_lock_token FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'delivery lock mismatch'; END IF;
  UPDATE public.social_calendar_items
  SET status='failed',
      publish_attempts=_next_attempt,
      last_attempt_at=now(),
      next_attempt_at=CASE WHEN _next_attempt >= max_attempts THEN NULL ELSE now() +
        CASE _next_attempt WHEN 1 THEN interval '5 minutes' WHEN 2 THEN interval '15 minutes' WHEN 3 THEN interval '1 hour' WHEN 4 THEN interval '4 hours' ELSE interval '1 day' END END,
      delivery_lock_token=NULL,
      delivery_locked_at=NULL,
      connector_result=COALESCE(_connector_result,'{}'::jsonb),
      error=left(COALESCE(NULLIF(btrim(_error),''),'delivery failed'),2000)
  WHERE id=_item_id
  RETURNING * INTO _result;
  INSERT INTO public.social_publish_events(item_id,run_id,event_type,worker_id,detail)
  VALUES (_item_id,_run_id,'failed',_result.last_worker_id,jsonb_build_object('attempt',_next_attempt,'next_attempt_at',_result.next_attempt_at,'error',_result.error));
  RETURN _result;
END;
$$;

REVOKE ALL ON FUNCTION public.social_attach_verified_render(uuid,uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.social_request_publication(uuid,timestamptz,text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.social_revoke_publication(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.social_attach_verified_render(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.social_request_publication(uuid,timestamptz,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.social_revoke_publication(uuid) TO authenticated;

REVOKE ALL ON FUNCTION public.social_claim_due_publications(text,integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.social_complete_publication(uuid,uuid,uuid,text,text,text,jsonb,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.social_fail_publication(uuid,uuid,uuid,text,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.social_claim_due_publications(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.social_complete_publication(uuid,uuid,uuid,text,text,text,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.social_fail_publication(uuid,uuid,uuid,text,jsonb) TO service_role;
