-- Activate the owner Admin product/media upload backend in a replay-safe way.
-- Existing products and existing image URLs are intentionally unchanged.

begin;

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket text not null default 'site-media',
  object_path text not null unique,
  public_url text not null,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes >= 0 and size_bytes <= 26214400),
  title text,
  alt_text text,
  tags text[] not null default '{}',
  usage_notes text,
  status text not null default 'active' check (status in ('active','archived')),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_asset_events (
  id bigint generated by default as identity primary key,
  media_asset_id uuid references public.media_assets(id) on delete set null,
  action text not null check (action in ('insert','update','delete')),
  actor_id uuid references auth.users(id) on delete set null,
  before_record jsonb,
  after_record jsonb,
  created_at timestamptz not null default now()
);

alter table public.media_assets
  add column if not exists verification_status text not null default 'pending',
  add column if not exists width_px integer,
  add column if not exists height_px integer,
  add column if not exists duration_ms integer,
  add column if not exists checksum_sha256 text,
  add column if not exists social_approved boolean not null default false,
  add column if not exists social_approved_at timestamptz,
  add column if not exists social_approved_by uuid references auth.users(id) on delete set null,
  add column if not exists thumbnail_bucket text,
  add column if not exists thumbnail_object_path text,
  add column if not exists thumbnail_url text,
  add column if not exists thumbnail_width_px integer,
  add column if not exists thumbnail_height_px integer,
  add column if not exists thumbnail_size_bytes bigint,
  add column if not exists thumbnail_generated_at timestamptz,
  add column if not exists responsive_widths integer[],
  add column if not exists responsive_format text,
  add column if not exists responsive_total_size_bytes bigint,
  add column if not exists responsive_generated_at timestamptz;

create index if not exists media_assets_status_created_idx
  on public.media_assets (status, created_at desc);
create index if not exists media_assets_tags_gin_idx
  on public.media_assets using gin (tags);
create index if not exists media_assets_social_ready_idx
  on public.media_assets (social_approved, verification_status, status, created_at desc);
create unique index if not exists media_assets_thumbnail_object_unique_idx
  on public.media_assets (thumbnail_bucket, thumbnail_object_path)
  where thumbnail_object_path is not null;
create index if not exists media_assets_missing_thumbnail_idx
  on public.media_assets (created_at desc)
  where mime_type like 'image/%' and thumbnail_url is null;
create index if not exists media_assets_responsive_backfill_idx
  on public.media_assets (created_at desc)
  where mime_type like 'image/%' and responsive_generated_at is null;

alter table public.media_assets enable row level security;
alter table public.media_asset_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='media_assets'
      and policyname='media_assets_admin_all'
  ) then
    create policy media_assets_admin_all on public.media_assets
      for all to authenticated
      using (public.has_role(auth.uid(), 'admin'::public.app_role))
      with check (public.has_role(auth.uid(), 'admin'::public.app_role));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='media_asset_events'
      and policyname='media_asset_events_admin_select'
  ) then
    create policy media_asset_events_admin_select on public.media_asset_events
      for select to authenticated
      using (public.has_role(auth.uid(), 'admin'::public.app_role));
  end if;
end $$;

revoke all on table public.media_assets from anon;
revoke all on table public.media_asset_events from anon;
grant select, insert, update, delete on table public.media_assets to authenticated;
grant select on table public.media_asset_events to authenticated;

create or replace function public.media_assets_before_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  service_call boolean := coalesce(auth.role() = 'service_role', false);
  verification_changed boolean := false;
begin
  if not service_call
     and (auth.uid() is null or not public.has_role(auth.uid(), 'admin'::public.app_role)) then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  if tg_op = 'UPDATE' then
    verification_changed :=
      old.verification_status is distinct from new.verification_status or
      old.width_px is distinct from new.width_px or
      old.height_px is distinct from new.height_px or
      old.duration_ms is distinct from new.duration_ms or
      old.checksum_sha256 is distinct from new.checksum_sha256;
    if verification_changed and not service_call then
      raise exception 'media verification fields are renderer/service controlled'
        using errcode = '42501';
    end if;
  elsif not service_call and new.verification_status <> 'pending' then
    raise exception 'new admin uploads must start pending verification'
      using errcode = '42501';
  end if;

  if new.verification_status not in ('pending','verified','rejected') then
    raise exception 'invalid media verification status';
  end if;

  if new.social_approved then
    if new.status <> 'active' or new.verification_status <> 'verified' then
      raise exception 'only active verified media can be approved for social use';
    end if;
    if tg_op = 'INSERT' or not coalesce(old.social_approved, false) then
      new.social_approved_at := now();
      new.social_approved_by := coalesce(auth.uid(), new.social_approved_by);
    end if;
  else
    new.social_approved_at := null;
    new.social_approved_by := null;
  end if;

  new.updated_at := now();
  if not service_call then
    new.updated_by := auth.uid();
    if tg_op = 'INSERT' then
      new.created_by := coalesce(new.created_by, auth.uid());
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.media_assets_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.media_asset_events (
    media_asset_id, action, actor_id, before_record, after_record
  ) values (
    coalesce(new.id, old.id),
    lower(tg_op),
    auth.uid(),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$$;

revoke all on function public.media_assets_before_write() from public;
revoke all on function public.media_assets_audit() from public;

drop trigger if exists media_assets_before_write_trigger on public.media_assets;
create trigger media_assets_before_write_trigger
  before insert or update on public.media_assets
  for each row execute function public.media_assets_before_write();

drop trigger if exists media_assets_audit_trigger on public.media_assets;
create trigger media_assets_audit_trigger
  after insert or update or delete on public.media_assets
  for each row execute function public.media_assets_audit();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  26214400,
  array[
    'image/jpeg','image/png','image/webp','image/gif','image/svg+xml',
    'application/pdf','video/mp4','video/webm'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_media_admin_insert'
  ) then
    create policy site_media_admin_insert on storage.objects
      for insert to authenticated
      with check (
        bucket_id='site-media'
        and public.has_role(auth.uid(), 'admin'::public.app_role)
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_media_admin_update'
  ) then
    create policy site_media_admin_update on storage.objects
      for update to authenticated
      using (
        bucket_id='site-media'
        and public.has_role(auth.uid(), 'admin'::public.app_role)
      )
      with check (
        bucket_id='site-media'
        and public.has_role(auth.uid(), 'admin'::public.app_role)
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='site_media_admin_delete'
  ) then
    create policy site_media_admin_delete on storage.objects
      for delete to authenticated
      using (
        bucket_id='site-media'
        and public.has_role(auth.uid(), 'admin'::public.app_role)
      );
  end if;
end $$;

notify pgrst, 'reload schema';

commit;
