insert into public.backend_activation_checkpoints(
  checkpoint_key, project_ref, auth_user_count, admin_role_count,
  recorded_migration_count, existing_objects
)
select
  'before_operations_orchestrator_20260714',
  'pvzjiozismyxqrzmtfbi',
  (select count(*) from auth.users),
  (select count(*) from public.user_roles where role='admin'),
  (select count(*) from supabase_migrations.schema_migrations),
  jsonb_build_object(
    'cron_job_count', (select count(*) from cron.job),
    'automation_enabled', (select enabled from public.automation_settings where id='default')
  )
on conflict (checkpoint_key) do nothing;

create table if not exists public.operations_control (
  id text primary key default 'default',
  enabled boolean not null default false,
  token_hash text,
  timezone text not null default 'Asia/Karachi',
  heartbeat_interval_minutes integer not null default 5 check (heartbeat_interval_minutes between 1 and 60),
  stale_run_minutes integer not null default 30 check (stale_run_minutes between 10 and 240),
  email_queue_enabled boolean not null default true,
  public_smoke_tests_enabled boolean not null default true,
  last_heartbeat_at timestamptz,
  last_daily_run_at timestamptz,
  last_email_run_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not enabled or token_hash is not null)
);

create table if not exists public.operations_runs (
  id uuid primary key default gen_random_uuid(),
  action text not null check (action in ('health','heartbeat','daily','email_queue','cleanup','manual_test')),
  trigger_source text not null default 'system' check (trigger_source in ('cron','manual','system')),
  status text not null default 'running' check (status in ('running','completed','partial','failed','skipped')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer,
  summary jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists public.operations_health_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid references public.operations_runs(id) on delete set null,
  overall_status text not null check (overall_status in ('healthy','degraded','blocked','failed')),
  components jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  blockers jsonb not null default '[]'::jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists operations_runs_action_started_idx on public.operations_runs(action, started_at desc);
create index if not exists operations_runs_status_started_idx on public.operations_runs(status, started_at desc);
create index if not exists operations_health_checked_idx on public.operations_health_snapshots(checked_at desc);

alter table public.operations_control enable row level security;
alter table public.operations_runs enable row level security;
alter table public.operations_health_snapshots enable row level security;

revoke all on public.operations_control from anon, authenticated;
revoke all on public.operations_runs from anon, authenticated;
revoke all on public.operations_health_snapshots from anon, authenticated;
grant select on public.operations_control to authenticated;
grant select on public.operations_runs to authenticated;
grant select on public.operations_health_snapshots to authenticated;

drop policy if exists operations_control_admin_select on public.operations_control;
create policy operations_control_admin_select on public.operations_control
for select to authenticated
using ((select public.has_role((select auth.uid()), 'admin'::public.app_role)));

drop policy if exists operations_runs_admin_select on public.operations_runs;
create policy operations_runs_admin_select on public.operations_runs
for select to authenticated
using ((select public.has_role((select auth.uid()), 'admin'::public.app_role)));

drop policy if exists operations_health_admin_select on public.operations_health_snapshots;
create policy operations_health_admin_select on public.operations_health_snapshots
for select to authenticated
using ((select public.has_role((select auth.uid()), 'admin'::public.app_role)));

insert into public.operations_control(id)
values ('default')
on conflict (id) do nothing;

comment on table public.operations_control is 'Private control plane for scheduled Irha backend operations.';
comment on table public.operations_runs is 'Operational execution history for cron, manual and system backend runs.';
comment on table public.operations_health_snapshots is 'Point-in-time backend, queue, provider and public-site health evidence.';
