-- Phase 5.4: verified social analytics, attribution and draft-only growth recommendations.
-- Source only. Apply during the final one-time backend activation.

ALTER TABLE public.social_calendar_items
  ADD COLUMN IF NOT EXISTS tracking_url text,
  ADD COLUMN IF NOT EXISTS utm_source text,
  ADD COLUMN IF NOT EXISTS utm_medium text,
  ADD COLUMN IF NOT EXISTS utm_campaign text,
  ADD COLUMN IF NOT EXISTS utm_content text,
  ADD COLUMN IF NOT EXISTS metrics_last_collected_at timestamptz;

CREATE TABLE IF NOT EXISTS public.social_metric_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES public.social_calendar_items(id) ON DELETE CASCADE,
  platform text NOT NULL CHECK (platform IN ('facebook','instagram','linkedin','tiktok')),
  external_post_id text,
  external_post_url text,
  snapshot_at timestamptz NOT NULL DEFAULT now(),
  impressions bigint NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  reach bigint NOT NULL DEFAULT 0 CHECK (reach >= 0),
  views bigint NOT NULL DEFAULT 0 CHECK (views >= 0),
  likes bigint NOT NULL DEFAULT 0 CHECK (likes >= 0),
  comments bigint NOT NULL DEFAULT 0 CHECK (comments >= 0),
  shares bigint NOT NULL DEFAULT 0 CHECK (shares >= 0),
  saves bigint NOT NULL DEFAULT 0 CHECK (saves >= 0),
  clicks bigint NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  profile_visits bigint NOT NULL DEFAULT 0 CHECK (profile_visits >= 0),
  followers_delta bigint NOT NULL DEFAULT 0,
  source text NOT NULL CHECK (source IN ('meta_graph','linkedin_api','tiktok_api','generic_gateway','manual_verified')),
  verified boolean NOT NULL DEFAULT false,
  provider_snapshot_key text,
  raw_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  collected_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (item_id, provider_snapshot_key)
);

CREATE TABLE IF NOT EXISTS public.social_attribution_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id uuid REFERENCES public.social_calendar_items(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (event_type IN ('landing','catalogue_request','inquiry','factory_call_request','sample_request','meeting_booked')),
  anonymous_session_hash text,
  lead_source_type text,
  lead_source_id uuid,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  destination_path text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.social_growth_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid REFERENCES public.social_calendar_items(id) ON DELETE CASCADE,
  recommendation_type text NOT NULL CHECK (recommendation_type IN ('collect_metrics','refresh_metrics','improve_cta','repurpose','pause_angle','review_tracking')),
  priority integer NOT NULL DEFAULT 50 CHECK (priority BETWEEN 1 AND 100),
  reason text NOT NULL,
  proposed_action text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','approved','dismissed','completed')),
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at timestamptz,
  completed_at timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS social_metric_item_snapshot_idx ON public.social_metric_snapshots (item_id, snapshot_at DESC);
CREATE INDEX IF NOT EXISTS social_metric_platform_snapshot_idx ON public.social_metric_snapshots (platform, snapshot_at DESC);
CREATE INDEX IF NOT EXISTS social_attribution_item_time_idx ON public.social_attribution_events (item_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS social_attribution_utm_idx ON public.social_attribution_events (utm_source, utm_campaign, occurred_at DESC);
CREATE INDEX IF NOT EXISTS social_growth_status_priority_idx ON public.social_growth_recommendations (status, priority DESC, created_at DESC);

ALTER TABLE public.social_metric_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_attribution_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_growth_recommendations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY social_metric_admin_read ON public.social_metric_snapshots
    FOR SELECT TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY social_attribution_admin_read ON public.social_attribution_events
    FOR SELECT TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY social_growth_admin_all ON public.social_growth_recommendations
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'))
    WITH CHECK (public.has_role(auth.uid(), 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

REVOKE ALL ON public.social_metric_snapshots, public.social_attribution_events, public.social_growth_recommendations FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.social_metric_snapshots, public.social_attribution_events FROM authenticated;
GRANT SELECT ON public.social_metric_snapshots, public.social_attribution_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.social_growth_recommendations TO authenticated;
GRANT ALL ON public.social_metric_snapshots, public.social_attribution_events, public.social_growth_recommendations TO service_role;

CREATE OR REPLACE FUNCTION public.social_growth_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS social_growth_touch_updated_at_trigger ON public.social_growth_recommendations;
CREATE TRIGGER social_growth_touch_updated_at_trigger
  BEFORE UPDATE ON public.social_growth_recommendations
  FOR EACH ROW EXECUTE FUNCTION public.social_growth_touch_updated_at();

REVOKE ALL ON FUNCTION public.social_growth_touch_updated_at() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.social_set_tracking(
  _item_id uuid,
  _tracking_url text,
  _utm_source text,
  _utm_medium text DEFAULT 'social',
  _utm_campaign text DEFAULT 'irha-social',
  _utm_content text DEFAULT NULL
)
RETURNS public.social_calendar_items
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE _result public.social_calendar_items;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  IF COALESCE(_tracking_url,'') !~ '^https://[^[:space:]]+$' THEN RAISE EXCEPTION 'valid HTTPS tracking URL required'; END IF;
  IF char_length(COALESCE(_utm_source,'')) < 2 OR char_length(_utm_source) > 80 THEN RAISE EXCEPTION 'valid UTM source required'; END IF;
  IF char_length(COALESCE(_utm_medium,'')) < 2 OR char_length(_utm_medium) > 80 THEN RAISE EXCEPTION 'valid UTM medium required'; END IF;
  IF char_length(COALESCE(_utm_campaign,'')) < 2 OR char_length(_utm_campaign) > 160 THEN RAISE EXCEPTION 'valid UTM campaign required'; END IF;

  UPDATE public.social_calendar_items
  SET tracking_url=_tracking_url,
      product_url=_tracking_url,
      utm_source=lower(btrim(_utm_source)),
      utm_medium=lower(btrim(_utm_medium)),
      utm_campaign=btrim(_utm_campaign),
      utm_content=COALESCE(NULLIF(btrim(_utm_content),''), id::text),
      publish_approved_by=NULL,
      publish_approved_at=NULL,
      delivery_mode='manual',
      next_attempt_at=NULL,
      status=CASE WHEN status IN ('published','publishing') THEN status ELSE 'draft' END
  WHERE id=_item_id
  RETURNING * INTO _result;

  IF NOT FOUND THEN RAISE EXCEPTION 'social calendar item not found'; END IF;
  RETURN _result;
END;
$$;

REVOKE ALL ON FUNCTION public.social_set_tracking(uuid,text,text,text,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.social_set_tracking(uuid,text,text,text,text,text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.social_record_manual_metrics(
  _item_id uuid,
  _snapshot_at timestamptz,
  _impressions bigint DEFAULT 0,
  _reach bigint DEFAULT 0,
  _views bigint DEFAULT 0,
  _likes bigint DEFAULT 0,
  _comments bigint DEFAULT 0,
  _shares bigint DEFAULT 0,
  _saves bigint DEFAULT 0,
  _clicks bigint DEFAULT 0,
  _profile_visits bigint DEFAULT 0,
  _followers_delta bigint DEFAULT 0,
  _evidence jsonb DEFAULT '{}'::jsonb
)
RETURNS public.social_metric_snapshots
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _item public.social_calendar_items;
  _result public.social_metric_snapshots;
  _key text;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  SELECT * INTO _item FROM public.social_calendar_items WHERE id=_item_id;
  IF NOT FOUND OR _item.status <> 'published' OR (_item.external_post_id IS NULL AND COALESCE(_item.external_post_url,'') !~ '^https://') THEN
    RAISE EXCEPTION 'published item with exact external evidence required';
  END IF;
  IF jsonb_typeof(COALESCE(_evidence,'{}'::jsonb)) <> 'object' OR COALESCE(_evidence,'{}'::jsonb) = '{}'::jsonb THEN
    RAISE EXCEPTION 'manual metric evidence is required';
  END IF;
  IF LEAST(_impressions,_reach,_views,_likes,_comments,_shares,_saves,_clicks,_profile_visits) < 0 THEN
    RAISE EXCEPTION 'metric values cannot be negative';
  END IF;
  _key := 'manual:' || _item_id::text || ':' || extract(epoch from date_trunc('minute',_snapshot_at))::bigint::text;

  INSERT INTO public.social_metric_snapshots(
    item_id,platform,external_post_id,external_post_url,snapshot_at,
    impressions,reach,views,likes,comments,shares,saves,clicks,profile_visits,followers_delta,
    source,verified,provider_snapshot_key,raw_metrics,collected_by
  ) VALUES (
    _item.id,_item.platform,_item.external_post_id,_item.external_post_url,_snapshot_at,
    _impressions,_reach,_views,_likes,_comments,_shares,_saves,_clicks,_profile_visits,_followers_delta,
    'manual_verified',true,_key,_evidence,auth.uid()
  )
  ON CONFLICT (item_id,provider_snapshot_key) DO UPDATE SET
    impressions=EXCLUDED.impressions,reach=EXCLUDED.reach,views=EXCLUDED.views,likes=EXCLUDED.likes,
    comments=EXCLUDED.comments,shares=EXCLUDED.shares,saves=EXCLUDED.saves,clicks=EXCLUDED.clicks,
    profile_visits=EXCLUDED.profile_visits,followers_delta=EXCLUDED.followers_delta,
    raw_metrics=EXCLUDED.raw_metrics,verified=true,collected_by=auth.uid()
  RETURNING * INTO _result;

  UPDATE public.social_calendar_items SET metrics_last_collected_at=_snapshot_at WHERE id=_item_id;
  RETURN _result;
END;
$$;

REVOKE ALL ON FUNCTION public.social_record_manual_metrics(uuid,timestamptz,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.social_record_manual_metrics(uuid,timestamptz,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,jsonb) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.social_set_recommendation_status(_id uuid, _status text)
RETURNS public.social_growth_recommendations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE _result public.social_growth_recommendations;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE='42501';
  END IF;
  IF _status NOT IN ('approved','dismissed','completed') THEN RAISE EXCEPTION 'invalid recommendation status'; END IF;
  UPDATE public.social_growth_recommendations
  SET status=_status,
      approved_by=CASE WHEN _status='approved' THEN auth.uid() ELSE approved_by END,
      approved_at=CASE WHEN _status='approved' THEN now() ELSE approved_at END,
      completed_at=CASE WHEN _status='completed' THEN now() ELSE completed_at END
  WHERE id=_id AND status IN ('open','approved')
  RETURNING * INTO _result;
  IF NOT FOUND THEN RAISE EXCEPTION 'recommendation cannot be updated'; END IF;
  RETURN _result;
END;
$$;

REVOKE ALL ON FUNCTION public.social_set_recommendation_status(uuid,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.social_set_recommendation_status(uuid,text) TO authenticated, service_role;

CREATE OR REPLACE VIEW public.social_growth_latest
WITH (security_invoker=true)
AS
SELECT
  item.id AS item_id,
  item.campaign_id,
  item.title,
  item.platform,
  item.content_type,
  item.status,
  item.external_post_id,
  item.external_post_url,
  item.published_at,
  item.tracking_url,
  item.metrics_last_collected_at,
  snapshot.id AS snapshot_id,
  snapshot.snapshot_at,
  snapshot.impressions,
  snapshot.reach,
  snapshot.views,
  snapshot.likes,
  snapshot.comments,
  snapshot.shares,
  snapshot.saves,
  snapshot.clicks,
  snapshot.profile_visits,
  snapshot.followers_delta,
  snapshot.source AS metric_source,
  snapshot.verified AS metric_verified,
  COALESCE(attribution.landing_count,0) AS landing_count,
  COALESCE(attribution.lead_count,0) AS attributed_lead_count
FROM public.social_calendar_items item
LEFT JOIN LATERAL (
  SELECT metric.* FROM public.social_metric_snapshots metric
  WHERE metric.item_id=item.id
  ORDER BY metric.snapshot_at DESC, metric.created_at DESC
  LIMIT 1
) snapshot ON true
LEFT JOIN LATERAL (
  SELECT
    count(*) FILTER (WHERE event_type='landing') AS landing_count,
    count(*) FILTER (WHERE event_type IN ('catalogue_request','inquiry','factory_call_request','sample_request','meeting_booked')) AS lead_count
  FROM public.social_attribution_events event
  WHERE event.item_id=item.id
) attribution ON true
WHERE public.has_role(auth.uid(), 'admin');

GRANT SELECT ON public.social_growth_latest TO authenticated;

CREATE OR REPLACE FUNCTION public.social_growth_health()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN jsonb_build_object('ok',false,'error','admin access required')
    ELSE jsonb_build_object(
      'ok',true,
      'database_ready',true,
      'published_items',(SELECT count(*) FROM public.social_calendar_items WHERE status='published'),
      'measured_items',(SELECT count(DISTINCT item_id) FROM public.social_metric_snapshots WHERE verified),
      'open_recommendations',(SELECT count(*) FROM public.social_growth_recommendations WHERE status='open'),
      'attribution_events',(SELECT count(*) FROM public.social_attribution_events)
    )
  END;
$$;

REVOKE ALL ON FUNCTION public.social_growth_health() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.social_growth_health() TO authenticated, service_role;
