-- Trace browser-level application errors without exposing private data.
-- Public callers can only execute the strict, rate-limited reporter function;
-- they cannot read or mutate incident rows.

BEGIN;

CREATE TABLE IF NOT EXISTS public.app_runtime_incidents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id text NOT NULL UNIQUE,
  route text NOT NULL DEFAULT '/',
  error_name text NOT NULL DEFAULT 'Error',
  error_message text,
  component_stack text,
  user_agent text,
  source_sha text,
  source text NOT NULL DEFAULT 'app_error_boundary',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.app_runtime_incidents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.app_runtime_incidents FROM anon, authenticated;

DROP POLICY IF EXISTS "Admins read app runtime incidents" ON public.app_runtime_incidents;
CREATE POLICY "Admins read app runtime incidents"
ON public.app_runtime_incidents
FOR SELECT
TO authenticated
USING (public.has_role((SELECT auth.uid()), 'admin'::public.app_role));

ALTER TABLE public.public_submission_events
  DROP CONSTRAINT IF EXISTS public_submission_events_action_check;
ALTER TABLE public.public_submission_events
  ADD CONSTRAINT public_submission_events_action_check
  CHECK (action IN ('submit_inquiry', 'submit_catalogue', 'create_upload', 'report_app_error'));

CREATE OR REPLACE FUNCTION public.consume_public_submission_limit(
  _fingerprint_hash text,
  _action text,
  _window_seconds integer,
  _max_count integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public'
AS $function$
DECLARE
  v_count integer;
BEGIN
  IF _fingerprint_hash IS NULL OR length(_fingerprint_hash) < 16 THEN RETURN false; END IF;
  IF _action NOT IN ('submit_inquiry', 'submit_catalogue', 'create_upload', 'report_app_error') THEN RETURN false; END IF;
  IF _window_seconds < 10 OR _window_seconds > 86400 OR _max_count < 1 OR _max_count > 100 THEN RETURN false; END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(_fingerprint_hash || ':' || _action, 0));
  SELECT count(*)::integer INTO v_count
  FROM public.public_submission_events
  WHERE fingerprint_hash = _fingerprint_hash
    AND action = _action
    AND created_at >= now() - make_interval(secs => _window_seconds);

  IF v_count >= _max_count THEN RETURN false; END IF;

  INSERT INTO public.public_submission_events (fingerprint_hash, action)
  VALUES (_fingerprint_hash, _action);

  DELETE FROM public.public_submission_events
  WHERE created_at < now() - interval '2 days';
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_public_app_incident(
  _incident_id text,
  _route text,
  _error_name text,
  _error_message text DEFAULT NULL,
  _component_stack text DEFAULT NULL,
  _user_agent text DEFAULT NULL,
  _source_sha text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public'
AS $function$
DECLARE
  v_headers jsonb := COALESCE(NULLIF(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  v_origin text := NULLIF(v_headers->>'origin', '');
  v_ip text;
  v_ua text;
  v_fingerprint text;
  v_incident text := upper(btrim(COALESCE(_incident_id, '')));
  v_route text;
  v_name text;
  v_message text;
  v_stack text;
  v_inserted integer := 0;
BEGIN
  IF v_incident !~ '^IRHA-[A-Z0-9]{6,20}-[A-Z0-9]{4,12}$' THEN RETURN false; END IF;

  IF v_origin IS NOT NULL
     AND v_origin NOT IN ('https://irhaapparels.com', 'https://www.irhaapparels.com')
     AND v_origin !~ '^https://[a-z0-9-]+\.lovable\.app$' THEN
    RETURN false;
  END IF;

  v_route := left(regexp_replace(COALESCE(NULLIF(btrim(_route), ''), '/'), '[[:cntrl:]]', ' ', 'g'), 500);
  IF left(v_route, 1) <> '/' THEN v_route := '/'; END IF;
  v_name := left(regexp_replace(COALESCE(NULLIF(btrim(_error_name), ''), 'Error'), '[[:cntrl:]]', ' ', 'g'), 120);
  v_message := NULLIF(left(regexp_replace(COALESCE(_error_message, ''), '[A-Za-z0-9_.-]{32,}', '[redacted]', 'g'), 1000), '');
  v_stack := NULLIF(left(regexp_replace(COALESCE(_component_stack, ''), '[[:cntrl:]&&[^\n\t]]', ' ', 'g'), 4000), '');
  v_ua := left(COALESCE(NULLIF(btrim(_user_agent), ''), v_headers->>'user-agent', 'unknown'), 500);

  v_ip := COALESCE(
    v_headers->>'cf-connecting-ip',
    v_headers->>'x-real-ip',
    split_part(COALESCE(v_headers->>'x-forwarded-for', 'unknown'), ',', 1),
    'unknown'
  );
  v_fingerprint := md5(v_ip || '|' || v_ua);

  IF NOT public.consume_public_submission_limit(v_fingerprint, 'report_app_error', 900, 3) THEN RETURN false; END IF;

  INSERT INTO public.app_runtime_incidents (
    incident_id, route, error_name, error_message, component_stack,
    user_agent, source_sha, source
  ) VALUES (
    v_incident,
    v_route,
    v_name,
    v_message,
    v_stack,
    v_ua,
    CASE WHEN COALESCE(_source_sha, '') ~ '^[0-9a-f]{40}$' THEN lower(_source_sha) ELSE NULL END,
    'app_error_boundary'
  )
  ON CONFLICT (incident_id) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  IF v_inserted > 0 THEN
    INSERT INTO public.crm_notifications (
      notification_type, source_type, source_id, title, body,
      severity, dedupe_key, metadata
    ) VALUES (
      'system',
      'system',
      NULL,
      'Website application error',
      v_incident || ' · ' || v_route || ' · ' || v_name,
      'attention',
      'app-incident:' || v_incident,
      jsonb_build_object(
        'incident_id', v_incident,
        'route', v_route,
        'error_name', v_name,
        'source_sha', CASE WHEN COALESCE(_source_sha, '') ~ '^[0-9a-f]{40}$' THEN lower(_source_sha) ELSE NULL END,
        'created_at', now()
      )
    )
    ON CONFLICT (dedupe_key) DO NOTHING;
  END IF;

  RETURN true;
END;
$function$;

REVOKE ALL ON FUNCTION public.record_public_app_incident(text,text,text,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_public_app_incident(text,text,text,text,text,text,text) TO anon, authenticated;

COMMENT ON FUNCTION public.record_public_app_incident(text,text,text,text,text,text,text) IS
  'Rate-limited, origin-checked, secret-redacting public runtime error reporter. Creates one admin system notification per incident reference.';

COMMIT;
