-- Phase 3 / Batch 3.1: Sales Pipeline tasks and activity audit.
-- Deferred per owner instruction. Apply once during final backend activation.

CREATE TABLE IF NOT EXISTS public.crm_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_type text NOT NULL CHECK (source_type IN ('inquiry', 'catalogue', 'prospect')),
  source_id uuid NOT NULL,
  title text NOT NULL CHECK (char_length(btrim(title)) BETWEEN 2 AND 240),
  notes text,
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'completed', 'cancelled')),
  due_at timestamptz,
  assigned_to text,
  completed_at timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'completed' AND completed_at IS NOT NULL) OR status <> 'completed')
);

CREATE INDEX IF NOT EXISTS crm_tasks_source_idx
  ON public.crm_tasks (source_type, source_id, status);
CREATE INDEX IF NOT EXISTS crm_tasks_due_open_idx
  ON public.crm_tasks (due_at, priority)
  WHERE status = 'open';
CREATE INDEX IF NOT EXISTS crm_tasks_assignee_open_idx
  ON public.crm_tasks (assigned_to, due_at)
  WHERE status = 'open';

CREATE TABLE IF NOT EXISTS public.crm_activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type text NOT NULL CHECK (source_type IN ('inquiry', 'catalogue', 'prospect')),
  source_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type IN (
    'stage_changed', 'follow_up_scheduled', 'task_created', 'task_completed',
    'note_added', 'email_drafted', 'email_sent', 'whatsapp_opened',
    'quotation_created', 'quotation_sent', 'sample_updated', 'meeting_scheduled',
    'record_updated', 'system'
  )),
  summary text NOT NULL CHECK (char_length(btrim(summary)) BETWEEN 2 AND 500),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_activity_events_source_created_idx
  ON public.crm_activity_events (source_type, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS crm_activity_events_type_created_idx
  ON public.crm_activity_events (event_type, created_at DESC);

ALTER TABLE public.crm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_activity_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='crm_tasks' AND policyname='crm_tasks_admin_all'
  ) THEN
    CREATE POLICY crm_tasks_admin_all ON public.crm_tasks
      FOR ALL TO authenticated
      USING (public.has_role(auth.uid(), 'admin'))
      WITH CHECK (public.has_role(auth.uid(), 'admin'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='crm_activity_events' AND policyname='crm_activity_events_admin_all'
  ) THEN
    CREATE POLICY crm_activity_events_admin_all ON public.crm_activity_events
      FOR ALL TO authenticated
      USING (public.has_role(auth.uid(), 'admin'))
      WITH CHECK (public.has_role(auth.uid(), 'admin'));
  END IF;
END $$;

REVOKE ALL ON TABLE public.crm_tasks FROM anon;
REVOKE ALL ON TABLE public.crm_activity_events FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.crm_tasks TO authenticated;
GRANT SELECT, INSERT ON TABLE public.crm_activity_events TO authenticated;

CREATE OR REPLACE FUNCTION public.crm_task_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin access required' USING ERRCODE = '42501';
  END IF;

  NEW.title := btrim(NEW.title);
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  IF TG_OP = 'INSERT' THEN
    NEW.created_by := COALESCE(NEW.created_by, auth.uid());
  END IF;
  IF NEW.status = 'completed' AND NEW.completed_at IS NULL THEN
    NEW.completed_at := now();
  ELSIF NEW.status <> 'completed' THEN
    NEW.completed_at := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS crm_task_before_write_trigger ON public.crm_tasks;
CREATE TRIGGER crm_task_before_write_trigger
  BEFORE INSERT OR UPDATE ON public.crm_tasks
  FOR EACH ROW EXECUTE FUNCTION public.crm_task_before_write();

CREATE OR REPLACE FUNCTION public.crm_task_activity_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.crm_activity_events (
      source_type, source_id, event_type, summary, metadata, actor_id
    ) VALUES (
      NEW.source_type,
      NEW.source_id,
      'task_created',
      'Task created: ' || NEW.title,
      jsonb_build_object('task_id', NEW.id, 'priority', NEW.priority, 'due_at', NEW.due_at),
      auth.uid()
    );
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'completed' THEN
    INSERT INTO public.crm_activity_events (
      source_type, source_id, event_type, summary, metadata, actor_id
    ) VALUES (
      NEW.source_type,
      NEW.source_id,
      'task_completed',
      'Task completed: ' || NEW.title,
      jsonb_build_object('task_id', NEW.id),
      auth.uid()
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS crm_task_activity_audit_trigger ON public.crm_tasks;
CREATE TRIGGER crm_task_activity_audit_trigger
  AFTER INSERT OR UPDATE ON public.crm_tasks
  FOR EACH ROW EXECUTE FUNCTION public.crm_task_activity_audit();

REVOKE ALL ON FUNCTION public.crm_task_before_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.crm_task_activity_audit() FROM PUBLIC;

-- Ensure the three CRM sources can support the canonical mobile pipeline.
ALTER TABLE public.inquiries
  ADD COLUMN IF NOT EXISTS priority text DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS assignee text,
  ADD COLUMN IF NOT EXISTS follow_up_at timestamptz,
  ADD COLUMN IF NOT EXISTS quotation_url text,
  ADD COLUMN IF NOT EXISTS sample_status text DEFAULT 'not_requested';

ALTER TABLE public.catalogue_leads
  ADD COLUMN IF NOT EXISTS priority text DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS assignee text,
  ADD COLUMN IF NOT EXISTS follow_up_at timestamptz,
  ADD COLUMN IF NOT EXISTS quotation_url text,
  ADD COLUMN IF NOT EXISTS sample_status text DEFAULT 'not_requested';

ALTER TABLE public.b2b_leads
  ADD COLUMN IF NOT EXISTS crm_status text DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS priority text DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS assignee text,
  ADD COLUMN IF NOT EXISTS follow_up_at timestamptz,
  ADD COLUMN IF NOT EXISTS quotation_url text,
  ADD COLUMN IF NOT EXISTS sample_status text DEFAULT 'not_requested';

CREATE INDEX IF NOT EXISTS inquiries_crm_pipeline_idx
  ON public.inquiries (status, priority, follow_up_at);
CREATE INDEX IF NOT EXISTS catalogue_leads_crm_pipeline_idx
  ON public.catalogue_leads (status, priority, follow_up_at);
CREATE INDEX IF NOT EXISTS b2b_leads_crm_pipeline_idx
  ON public.b2b_leads (crm_status, priority, follow_up_at);
